Big Refactor & Improvements
ice-blockchain/eskimo pull request #11
Opened 2022-06-15 23:50 UTC by victor-oancea-leftclick-io

alot of improvements and changes... to many to describe

2022-06-17 09:28 UTC, nusanovkornilov-leftclick requested changes

2022-06-17 09:28 UTC, nusanovkornilov-leftclick commented on users/phone_number.go
> -	// According to Fedor, we're deactivating used code this way, to keep unique values in database.
Are you sure we dont need comment about code deactivation? It is a little bit unclear at the first view why we're updating code field with userID

2022-06-17 11:40 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/devices.go
> +func (s *service) GetDeviceLocation(ctx context.Context, r server.ParsedRequest) server.Response {
this is an exception cuz it requires ip2location

2022-06-17 17:46 UTC, antonh21 approved these changes
Nothing special, only adding info to `application.yaml` and little stylish fixes in the patch below. Don't see any problems except.
```
diff --git a/application.yaml b/application.yaml
index 613655a..f452487 100644
--- a/application.yaml
+++ b/application.yaml
@@ -24,6 +24,11 @@ users:
   db:
     spaces:
       - USERS
+      - PHONE_NUMBER_VALIDATIONS
+      - DAYS
+      - USERS_PER_COUNTRY
+      - DEVICE_SETTINGS
+      - DEVICE_METADATA
     urls:
       - localhost:3301
     user: admin
diff --git a/users/top_countries.go b/users/top_countries.go
index 50f2837..12d6f80 100644
--- a/users/top_countries.go
+++ b/users/top_countries.go
@@ -59,5 +59,5 @@ func (r *repository) incrementOrDecrementCountryUserCount(ctx context.Context, c
 	insertTuple := &CountryStatistics{Country: country, UserCount: 1}
 
 	return errors.Wrapf(r.db.UpsertAsync("USERS_PER_COUNTRY", insertTuple, arOp).GetTyped(&[]*CountryStatistics{}),
-		"error changing country count for country%v & operation:%v", country, operation)
+		"error changing country count for country:%v & operation:%v", country, operation)
 }
diff --git a/users/users_referrals.go b/users/users_referrals.go
index 1eddf34..563cdb5 100644
--- a/users/users_referrals.go
+++ b/users/users_referrals.go
@@ -53,7 +53,7 @@ func (r *repository) GetReferrals(ctx context.Context, arg *GetReferralsArg) (*R
 				'' 																					   AS country
 		FROM USERS u
 				%[2]v
-		WHERE u.id = :user_id
+		WHERE u.id = :userId
 
 		UNION ALL
 
@@ -75,12 +75,12 @@ func (r *repository) GetReferrals(ctx context.Context, arg *GetReferralsArg) (*R
 				referrals.country                                                                       AS country
 		FROM USERS u
 				%[2]v
-		WHERE u.id = :user_id
+		WHERE u.id = :userId
 		ORDER BY (phone_number_ != '' AND phone_number_ != null) DESC,
 				 referrals.created_at DESC
 		LIMIT %[3]v OFFSET :offset`, cfg.PictureStorage.URLDownload, referralTypeJoin, arg.Limit)
 	params := map[string]interface{}{
-		"user_id":  arg.UserID,
+		"userId":   arg.UserID,
 		"nowNanos": time.Now(),
 		"offset":   arg.Offset,
 	}
```

2022-06-21 13:00 UTC, victor-oancea-leftclick-io commented on .gitignore
>  *.exe
needs to be tested first

2022-06-23 15:09 UTC, kfedor approved these changes

2022-06-23 15:29 UTC, victor-oancea-leftclick-io commented on users/users_get.go
> +			count(distinct t1.id) + count(t2.id) 	AS total_referral_count
not sure exactly how to handle that atm, it could either be itself or null

2022-06-23 15:32 UTC, victor-oancea-leftclick-io commented on users/internal/device/metadata/contract.go
> +		LastUpdateTime   *time.Time `json:"lastUpdateTime"`
debug & fix it

2022-06-23 15:33 UTC, victor-oancea-leftclick-io commented on users/internal/device/metadata/metadata.go
> +		return errors.Wrapf(err, "failed to get location information based on IP %v to replace device metadata", ip.String())
we take only country & city from i2location on user registration, why?

2022-06-23 15:33 UTC, victor-oancea-leftclick-io commented on users/internal/device/metadata/metadata.go
> +	var result []*DeviceMetadata
?

2022-06-24 07:07 UTC, nusanovkornilov-leftclick approved these changes

2022-06-24 08:44 UTC, antonh21 approved these changes
Noticed only some things as 
```
-if err != nil {
	log.Panic(errors.Wrapf(err, "crypto random generator failed"))
-}
```
No need to use err check as log returns if error is nil, but it is option how to use, no sense to block the PR by such little changes.

2022-06-24 08:44 UTC, merged