Feature quiz reset
ice-blockchain/eskimo pull request #111
Opened 2024-01-29 21:18 UTC by ice-dionysos

2024-01-30 13:21 UTC, ice-ares requested changes

2024-01-30 13:21 UTC, ice-ares commented on kyc/quiz/DDL.sql
> +    primary key (user_id, started_at, created_at)
I dont think u need created at there

2024-01-30 13:21 UTC, ice-ares commented on kyc/quiz/contract.go
> +		TimeWindow                stdlibtime.Duration `yaml:"time-window" mapstructure:"time-window"`                  //nolint:tagliatelle // .
What are those for?

2024-01-30 13:21 UTC, ice-ares commented on kyc/quiz/quiz.go
> +		return ErrInvalidKYCState
Dont u need the not available one here?

2024-01-30 13:21 UTC, ice-ares commented on kyc/quiz/quiz.go
> +		_, err = r.finishUnfinishedSession(ctx, r.DB, now, userID)
tx?

2024-01-30 13:21 UTC, ice-ares commented on kyc/quiz/quiz.go
> +		_, err = r.finishUnfinishedSession(ctx, r.DB, now, userID)
Also, are u calling modify user to block quiz here ?

2024-01-30 13:21 UTC, ice-ares commented on kyc/quiz/quiz.go
> +		return nil
Panic

2024-01-30 13:21 UTC, ice-ares commented on kyc/quiz/quiz.go
> +insert into quiz_resets
U said u had a trigger for that

2024-01-30 13:21 UTC, ice-ares commented on kyc/quiz/quiz.go
> +	const stmt = `select false as val from quiz_resets where user_id = $1 and cardinality(resets) > $2`
I think its >=

2024-01-30 14:06 UTC, ice-dionysos commented on kyc/quiz/quiz.go
> +insert into quiz_resets
I did, but after testing decided to leave it like this because that's more testable/simple.

2024-01-30 14:09 UTC, ice-dionysos commented on kyc/quiz/quiz.go
> +		return ErrInvalidKYCState
:thinking: Well, may be.

2024-01-30 14:27 UTC, ice-cronus commented on kyc/quiz/quiz.go
> +	_, err = storage.Exec(ctx, tx, stmtReset, userID, now.Time)
should not it be ended_at? To make sure it is in the future in comparsion with freezer's last balance updated at?

2024-01-30 14:30 UTC, ice-ares commented on kyc/quiz/quiz.go
> +	_, err = storage.Exec(ctx, tx, stmtReset, userID, now.Time)
no, cuz if we put a date in the past there, balance last updated at will already be after it and u'll treat it as if it was already disabled

2024-01-30 14:32 UTC, ice-ares commented on kyc/quiz/quiz.go
> +	_, err = storage.Exec(ctx, tx, stmtReset, userID, now.Time)
we might even need to add some delta to it, to account for some network/processing delays

2024-01-30 15:03 UTC, ice-ares commented on kyc/quiz/quiz.go
> +	const stmt = `select false as val from quiz_resets where user_id = $1 and cardinality(resets) > $2`
actually no, > is fine

2024-01-30 15:19 UTC, ice-ares commented on kyc/quiz/quiz.go
> +	const stmt = `select false as val from quiz_resets where user_id = $1 and cardinality(resets) > $2`
cuz I need to be able to set 0 as max resets allowed (meaning an entry in quiz_resets with 1 element in resets array would mean quiz is disabled)

2024-01-30 15:28 UTC, ice-dionysos commented on kyc/quiz/quiz.go
> +		_, err = r.finishUnfinishedSession(ctx, r.DB, now, userID)
>tx?

Fixed


>are u calling modify user to block quiz here ?

Yeah, I do call modifyUser().

2024-01-30 15:51 UTC, ice-ares commented on kyc/quiz/quiz.go
> +		_, err = r.finishUnfinishedSession(ctx, r.DB, now, userID)
yea, but with blocked true?

2024-01-30 15:52 UTC, ice-ares commented on kyc/quiz/quiz.go
> +		_, err = r.finishUnfinishedSession(ctx, r.DB, now, userID)
if thats the last one that triggers disabling

2024-01-30 18:23 UTC, IvayiloGeorgiev commented
> 

✅ Потвърждавам акаунта си в @ice_blockchain с прякора: "ivo831909"

👉 Научете повече за "Децентрализираното бъдеще", което #IceNetwork изгражда. 👇

#Binance #HTX #KuCoin #OKX #Bybit #Gateio #Upbit #Crypto #Blockchain #Web3 #Altcoin #Bitcoin #Ethereum #BNB

2024-01-31 13:31 UTC, ice-ares requested changes

2024-01-31 13:31 UTC, ice-ares commented on kyc/quiz/quiz.go
> +				qr.user_id,
I think u.id would be enough

2024-01-31 13:31 UTC, ice-ares commented on kyc/quiz/quiz.go
> +	if r.config.MaxResetCount == 0 {
No, 0 is a valid value

2024-01-31 13:31 UTC, ice-ares commented on kyc/quiz/quiz.go
> +	if status.KYCQuizAvailabilityEndedAt.Before(*now.Time) {
Or maybe its the last failed attempt. It doesnt just have to be outside that window. 

That should be the case for all the flows: if u just failed the last attempt or u outside of the window => reset should happen

2024-01-31 13:31 UTC, ice-ares commented on kyc/quiz/quiz.go
> +	count, err := storage.Get[int](ctx, tx, "select count(1) from failed_quiz_sessions where user_id = $1", userID)
U need to add also check that started at is after a specific date. Check the sql i created yesterday

All flows that use that table need it cuz we only care about failed attempts after a specific date -- we ignore the old ones--

2024-01-31 13:54 UTC, ice-dionysos commented on kyc/quiz/quiz.go
> +				qr.user_id,
Nope
```
ERROR: column "qr.user_id" must appear in the GROUP BY clause or be used in an aggregate function (SQLSTATE 42803)
```

2024-01-31 14:26 UTC, ice-ares commented on kyc/quiz/quiz.go
> +				qr.user_id,
Then use only user ids from all those tables

2024-01-31 15:11 UTC, ice-myles commented on kyc/quiz/quiz.go
> +func (r *repositoryImpl) IsUserOutOfTimeWindow(user *users.User) bool {
Unused function?

2024-01-31 15:11 UTC, ice-myles commented on kyc/quiz/quiz.go
> +		err = ErrUnknownSession
Why here is unknown session when it's just user not found as session information is taken by LEFT JOIN?

2024-01-31 15:11 UTC, ice-myles commented on kyc/quiz/quiz.go
> +	if r.config.GlobalStartDate == "" {
Why not to do this at `mustLoadConfig` function? At least it will panic on the startup instead of SQL call where is the only place this function is called (except unused function).

2024-01-31 15:11 UTC, ice-myles commented on kyc/quiz/quiz.go
> +		reRead = true
Why reRead is changed here, then some actions can be done with the status, and only in the end status is updated? Don't need to update status before 
```
if status.KYCQuizAvailabilityEndedAt.Before(*now.Time) {
```
call if reRead is true?

2024-01-31 15:11 UTC, ice-myles commented on kyc/quiz/quiz.go
> +			return errors.Wrap(err, "failed to get session data")
Do you need wrapping here as you don't use it at other places inside this transaction?

2024-01-31 15:15 UTC, ice-dionysos commented on kyc/quiz/quiz.go
> +	if status.KYCQuizAvailabilityEndedAt.Before(*now.Time) {
We do reset here for two flows:
- for unfinished session, we'll finish it and do reset (if required)
- time window check and reset

2024-01-31 15:16 UTC, ice-dionysos commented on kyc/quiz/quiz.go
> +func (r *repositoryImpl) IsUserOutOfTimeWindow(user *users.User) bool {
Yup

2024-01-31 15:24 UTC, ice-myles commented on kyc/quiz/quiz.go
> +			_, prepareErr := r.prepareUserForReset(ctx, userID, now, tx)
Why don't you use `blocked` value from function and just send `true` to modify user all the time?

2024-01-31 15:24 UTC, ice-dionysos commented on kyc/quiz/quiz.go
> +		err = ErrUnknownSession
Here we are just replacing NotFound error with our own. That's better to tests/maintain.

2024-01-31 15:31 UTC, ice-dionysos commented on kyc/quiz/quiz.go
> +			_, prepareErr := r.prepareUserForReset(ctx, userID, now, tx)
`blocked` is always true here.

2024-01-31 15:32 UTC, ice-dionysos commented on kyc/quiz/quiz.go
> +		reRead = true
`KYCQuizAvailabilityEndedAt` is a constant value. Even if we do `reRead` it will have the same value.

2024-01-31 15:36 UTC, ice-dionysos commented on kyc/quiz/quiz.go
> +			return errors.Wrap(err, "failed to get session data")
That's just to make the error message more detailed.

2024-01-31 15:42 UTC, ice-myles commented on kyc/quiz/quiz.go
> +			_, prepareErr := r.prepareUserForReset(ctx, userID, now, tx)
Then what is the sense to return bool from `prepareUserForReset` function?

2024-01-31 16:01 UTC, ice-dionysos commented on kyc/quiz/quiz.go
> +			_, prepareErr := r.prepareUserForReset(ctx, userID, now, tx)
Well, good point :)

2024-02-01 07:40 UTC, ice-ares commented on kyc/quiz/.testdata/application.yaml
> +  globalStartDate: 2024-01-01
U're missing the availability one

2024-02-01 07:40 UTC, ice-ares commented on kyc/quiz/DDL.sql
> +CREATE INDEX IF NOT EXISTS quiz_sessions_history_ended_at_idx ON quiz_sessions_history (ended_at DESC);
What do u need this for? U can just use the resets table and the cardinality of the array to see if u've reached the maximum number of resets

2024-02-01 07:40 UTC, ice-ares commented on kyc/quiz/DDL.sql
> +create table if not exists quiz_sessions_history
Add a failed_ prefix

2024-02-01 07:40 UTC, ice-ares commented on kyc/quiz/quiz.go
> +				u.created_at
U.id?

2024-02-01 10:42 UTC, ice-ares submitted a review, later dismissed

2024-02-01 15:35 UTC, merged