Common integration tests functionality
ice-blockchain/eskimo pull request #12
Opened 2022-06-30 17:52 UTC by antonh21

This PR is to create the common integration tests functionality to use it at the next PRs not to do the repeated things. 

Blocked by [wintr #7](https://github.com/ice-blockchain/wintr/pull/7) and [wintr #9](https://github.com/ice-blockchain/wintr/pull/9) should be merged first.

2022-07-04 17:35 UTC, victor-oancea-leftclick-io commented on application.yaml
> +  ip2LocationBinaryPath: .testdata/IP-COUNTRY-REGION-CITY-LATITUDE-LONGITUDE-ZIPCODE-TIMEZONE-ISP-DOMAIN-NETSPEED-AREACODE-WEATHER-MOBILE-ELEVATION-USAGETYPE-SAMPLE.BIN
This is not part of the production code

2022-07-04 17:36 UTC, victor-oancea-leftclick-io commented on application.yaml
> +    certPath: .testdata/localhost.crt
Will running locally still work?

2022-07-04 17:37 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/Dockerfile
> +RUN make download-ip2location-sample
Never dirty up production code with test code!

2022-07-04 17:40 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/integration_test.go
> +			fmt.Sprintf("%v%v", testdataPath, testCfg.IP2LocationBinaryPath),
Nope. You provide those mouting points from fixtures in users

2022-07-04 17:42 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/integration_test.go
> +type http2TestClient struct {
There’s alot of code here that can be in fixtures in wintr

2022-07-04 21:16 UTC, antonh21 commented on application.yaml
> +  ip2LocationBinaryPath: .testdata/IP-COUNTRY-REGION-CITY-LATITUDE-LONGITUDE-ZIPCODE-TIMEZONE-ISP-DOMAIN-NETSPEED-AREACODE-WEATHER-MOBILE-ELEVATION-USAGETYPE-SAMPLE.BIN
Why?
users.go:
```
func StartProcessor(ctx context.Context, cancel context.CancelFunc) Processor {
...
deviceMetadataRepository := devicemetadata.New(db, mbProducer)
```

metadata.go:
```
func New(db tarantool.Connector, mb messagebroker.Client) (r DeviceMetadataRepository) {
                ...
		r.(*repository).ip2LocationDB, err = ip2location.OpenDB(cfg.IP2LocationBinaryPath)
		log.Panic(errors.Wrap(err, "unable to open ip2location database"))
	}
```

No IP2Location binary == panic.
You don't separate test and production code for this binary. Why should it be not part of the production code?

2022-07-04 21:16 UTC, antonh21 commented on application.yaml
> +    certPath: .testdata/localhost.crt
You are right. Didn't check local launching. Thanks.

2022-07-04 21:18 UTC, antonh21 commented on cmd/eskimo-hut/Dockerfile
> +RUN make download-ip2location-sample
But this docker file is used for the testcontainers. And no IP2Location binary == panic. It means that we should download and unzip this binary. Should be used another docker file for that?

2022-07-04 21:18 UTC, antonh21 commented on cmd/eskimo-hut/integration_test.go
> +type http2TestClient struct {
By the way yes, thanks.

2022-07-05 04:28 UTC, victor-oancea-leftclick-io commented on application.yaml
> +  ip2LocationBinaryPath: .testdata/IP-COUNTRY-REGION-CITY-LATITUDE-LONGITUDE-ZIPCODE-TIMEZONE-ISP-DOMAIN-NETSPEED-AREACODE-WEATHER-MOBILE-ELEVATION-USAGETYPE-SAMPLE.BIN
Separation of concerns! I didnt spend time decoupling stuff and making em loosely coupled so that you couple them back again. 

Anything about ip2location belongs in 1 place and one place only. And thats not the cmds.

2022-07-05 04:29 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/Dockerfile
> +RUN make download-ip2location-sample
You dont need to do that in a docker file, you can mount it

2022-07-05 05:38 UTC, victor-oancea-leftclick-io requested changes

2022-07-05 05:38 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/integration_test.go
> +	server.New(new(service), applicationYamlKey, "/users")
Thts not the path

2022-07-05 05:38 UTC, victor-oancea-leftclick-io commented on cmd/eskimo/.testdata/application.yaml
> +    urlUpload: https://storage.bunnycdn.com/ice-staging/profile
Not needed

2022-07-05 05:38 UTC, victor-oancea-leftclick-io commented on cmd/eskimo/.testdata/application.yaml
> +    accessKey: access_key_hidden
Not needed

2022-07-05 05:38 UTC, victor-oancea-leftclick-io commented on cmd/eskimo/.testdata/application.yaml
> +  phoneNumberValidation:
Not needed

2022-07-15 13:14 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/integration_test.go
> +	mbConnector = messagebrokerfixture.NewTestConnector(applicationYAMLKey, defaultOrder)
I was expecting this. You guys still don't understand the concept of separation of concerns, single responsibility principle. 

From the outside world `users` is a black box, you don't expose its implementation/contents outside of it.

2022-07-15 13:43 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/integration_test.go
> +	mbConnector = messagebrokerfixture.NewTestConnector(applicationYAMLKey, defaultOrder)
exactly

2022-07-15 18:09 UTC, victor-oancea-leftclick-io approved these changes

2022-07-15 18:37 UTC, merged