Simplified email registration
ice-blockchain/eskimo pull request #132
Opened 2024-05-21 19:53 UTC by ice-myles

Auth was changed from magic link to code. Removed status endpoint as obsolete. Separate endpoint for reset email change due to it requires to use jwt token payload at the email.

Requires to update translations.

2024-05-21 20:15 UTC, ice-ares commented on cmd/eskimo-hut/api/docs.go
> +        "/auth/ResetEmailChange": {
Start with lowercase r

2024-05-21 20:15 UTC, ice-ares commented on cmd/eskimo-hut/auth.go
> +//	@Router			/auth/ResetEmailChange [POST].
lowercase r

2024-05-22 08:26 UTC, ice-cronus submitted a review, later dismissed

2024-05-22 08:26 UTC, ice-cronus commented on cmd/eskimo-hut/auth.go
> +func (s *service) ResetEmailChange(
we'll need not to forget to notify web-app devs as well that they shoud submit that confirmation code and payload to another endpoint from that code-input web-app page (if it still exists).

2024-05-22 08:26 UTC, ice-cronus commented on auth/email_link/DDL.sql
> +           otp                                    TEXT,
I am not sure if we need that otp and email payloads at all anymore, cuz it was to check if user clicked right link / email (and confirmation code was 2nd factor). And for now we identify it only by code, so otp and magicLink token seems to be redundant. But we can keep at as is as it requires less modifications (including web-app side)

2024-05-22 14:31 UTC, ice-cronus requested changes

2024-05-22 14:31 UTC, ice-cronus commented on auth/email_link/link_verify.go
> +	tokens, err = c.generateTokens(els.TokenIssuedAt, els, els.IssuedTokenSeq+1)
this approach is less atomic, you need returning most probably

2024-05-22 14:51 UTC, ice-cronus approved these changes

2024-05-22 15:43 UTC, merged