create user integration tests
ice-blockchain/eskimo pull request #16
Opened 2022-07-18 10:43 UTC by nusanovkornilov-leftclick

User creation endpoints tests ( verification of response, http status codes)
Internal tests for users package related to user creation

2022-07-18 10:53 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users.go
> +// @Failure      404            {object}  server.ErrorResponse  "referredBy points to non-existing user"
nope, its handled via a 400

2022-07-18 10:54 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users.go
> +// @Failure      404            {object}  server.ErrorResponse  "referredBy points to non-existing user"
oops, nvm, my bad

2022-07-18 10:56 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users_test.go
> +func testCreateUser(ctx context.Context, tb testing.TB, tr fixture.TestConnector, reqBody, expected string, expectedStatus int) {
you don't need tr

2022-07-18 10:57 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users_test.go
> +func testCreateUser(ctx context.Context, tb testing.TB, tr fixture.TestConnector, reqBody, expected string, expectedStatus int) {
reqBody, expectedRespBody string, expectedRespStatus

2022-07-18 10:58 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users_test.go
> +	assert.Contains(tb, body, expected)
match exact with regex, including the order of fields, check jazmine/dexter/ricky for examples

2022-07-18 10:59 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users_test.go
> +	require.Greater(tb, l, 0)
assert

2022-07-18 10:59 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users_test.go
> +	require.Equal(tb, http.Header{"Content-Type": []string{"application/json; charset=utf-8"}}, headers)
assert

2022-07-18 11:01 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users_test.go
> +	testCreateUser(ctx, t, serverConnector,
run them with t.Run to run em in parallel, the ones that you can, cuz with ur current setup, first require.XXX stops the test, without checking any of the next tests

2022-07-18 11:04 UTC, victor-oancea-leftclick-io commented on users/users_add_test.go
> +func serializeUserSnapshot(t *testing.T, userSnapshot *UserSnapshot) string {
receiver method on *UserSnapshot named `requireMarshallJSON`

2022-07-18 11:05 UTC, victor-oancea-leftclick-io commented on users/users_add_test.go
> +func getTestUserData(userID UserID, referredBy string) *User {
bogusUser

2022-07-18 11:06 UTC, victor-oancea-leftclick-io commented on users/users_add_test.go
> +func getCreateUserArg(user *User, ip net.IP) *CreateUserArg {
receiver method on User, named createUserArg

2022-07-18 11:08 UTC, victor-oancea-leftclick-io commented on users/users_add_test.go
> +		Value: snapshotBytes,
inline

2022-07-18 11:10 UTC, victor-oancea-leftclick-io commented on users/users_add_test.go
> +func processAndVerifyMessageBrokerPublishing(ctx context.Context, t *testing.T, userSnapshot *UserSnapshot) {
create a varargs out of this userSnapshot ...*UserSnapshot)

and name it `verifyUserSnapshotMessages`

2022-07-18 11:11 UTC, victor-oancea-leftclick-io commented on users/users_add_test.go
> +	if errorMatcher == "" {
make this `error` and expect `errors.Is(...)`

2022-07-18 11:14 UTC, victor-oancea-leftclick-io commented on users/users_add_test.go
> +func testCreateAndGetUser(ctx context.Context, t *testing.T, arg *CreateUserArg, errorMatcher string) *User {
receiver method on * CreateUserArg, rename it to verifyCreateUser -- cuz get is a helper

Also, keep in mind, the `test` keyword is reserved for the actual tests, if you have helpers, you usually use verify/assert/require/check

2022-07-18 11:15 UTC, victor-oancea-leftclick-io commented on users/users_add_test.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
testDeadline

2022-07-18 11:16 UTC, victor-oancea-leftclick-io commented on users/users_add_test.go
> +	assert.NotNil(t, userProfile.CreatedAt)
>= something, always cover as much as possible, binary checks are not enough

2022-07-18 11:18 UTC, victor-oancea-leftclick-io commented on users/users_add_test.go
> +func TestUserStorage_NewUser(t *testing.T) {
TestUserRepository_CreateUser

2022-07-18 11:20 UTC, victor-oancea-leftclick-io commented on users/users_add_test.go
> +		require.Error(t, err, errorMatcher)
check that get `userProfile, err := usersRepository.(*repository).getUserByID(ctx, arg.User.ID)` returns 404 as well

2022-07-18 11:21 UTC, victor-oancea-leftclick-io commented on users/top_countries_test.go
> +func TestUserStorage_NewUser_CountryStatsUpdate(t *testing.T) {
pattern is Test{Interface/Struct}_{Method}_{Usecase}

2022-07-18 11:23 UTC, victor-oancea-leftclick-io commented on users/top_countries_test.go
> +func TestUserStorage_NewUser_CountryStatsUpdate(t *testing.T) {
also, split it into multiple tests so that you have 1 test/usecase

2022-07-18 11:24 UTC, ice-ares requested changes
x

2022-07-18 11:26 UTC, victor-oancea-leftclick-io commented on users/users_add_test.go
> +	assert.NotNil(t, userProfile.CreatedAt)
wintr/time is a super set of sdlib time, so what you can do with sdlib time, you can do with wintr/time.

You don't have to mock everything, just look into the impl of wintr/time

2022-07-19 07:12 UTC, nusanovkornilov-leftclick commented on users/users_add_test.go
> +		require.Error(t, err, errorMatcher)
I think it'll be better to do with read tests, isn't it? Not related to user creation

2022-07-19 07:28 UTC, victor-oancea-leftclick-io commented on users/users_add_test.go
> +		require.Error(t, err, errorMatcher)
Actually, dont use that, use the dbConnector directly to verify that it was persisted properly

2022-07-19 10:23 UTC, victor-oancea-leftclick-io approved these changes

2022-07-19 10:23 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users_test.go
> +func TestUserCreation(t *testing.T) {
have you exhausted all scenarios? did you triple check?

2022-07-19 10:23 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users_test.go
> +			`{"email": "testuser@example.com", "phoneNumber": "+123456789","phoneNumberHash": "","username": "test"}`,
email is optional

2022-07-19 10:23 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users_test.go
> +func TestUserCreation(t *testing.T) {
rename file to users_create_test.go

2022-07-19 10:23 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users_test.go
> +			// nolint:lll // Long response here.
nope, thats very important, format it

2022-07-19 10:23 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users_test.go
> +			fmt.Sprintf(`{"createdAt":%[1]q,"updatedAt":%[1]q,"id":"did:ethr:0x4B73C58370AEfcEf86A6021afCDe5673511376B2","username":"test","profilePictureUrl":"default-user-image.jpg","country":"-","city":"Th
profilepictureurl should be an url

2022-07-19 10:23 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users_test.go
> +			fmt.Sprintf(`{"createdAt":%[1]q,"updatedAt":%[1]q,"id":"did:ethr:0x4B73C58370AEfcEf86A6021afCDe5673511376B2","username":"test","profilePictureUrl":"default-user-image.jpg","country":"-","city":"Th
use some proper ip

2022-07-19 10:23 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users_test.go
> +			`{"email": "testuser@example.com","username": "test"}`,
thats not how you prove it

2022-07-19 10:23 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users_test.go
> +			`CONFLICT_WITH_ANOTHER_USER`, 409)
code is not enough, check data as well

2022-07-19 10:23 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users_test.go
> +			`{"email": "testuser@example.com", "username": "user%name"}`,
you could try fuzzying

2022-07-19 10:23 UTC, victor-oancea-leftclick-io commented on users/users_add_test.go
> +
dont use synonyms, its {targetFile}_test

2022-07-19 10:23 UTC, victor-oancea-leftclick-io commented on users/users_add_test.go
> +		net.IPv4(72, 229, 28, 185), // Example address in US, New York City.
extract to var, and inline the rest

2022-07-19 10:23 UTC, victor-oancea-leftclick-io commented on users/users_add_test.go
> +	user := bogusUser(userID, "").createUserArg(
inline userID

2022-07-19 10:23 UTC, victor-oancea-leftclick-io commented on users/users_add_test.go
> +	assert.Greater(t, user.CreatedAt.Unix(), int64(0))
still not enough

2022-07-19 10:23 UTC, victor-oancea-leftclick-io commented on users/users_snapshot_test.go
> +	assert.Equal(t, 1, len(countryStats))
lets try to compare whole objects/arrays

2022-07-19 10:23 UTC, victor-oancea-leftclick-io requested changes
oops

2022-07-19 10:32 UTC, nusanovkornilov-leftclick commented on cmd/eskimo-hut/devices.go
> -// @Param        userId          path      string                true  "ID of the user"
thats because of swag update. I called chackGenerate, it failed, used generate and it reformatted a part of the project

2022-07-19 12:45 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users_test.go
> +			fmt.Sprintf(`{"createdAt":%[1]q,"updatedAt":%[1]q,"id":"did:ethr:0x4B73C58370AEfcEf86A6021afCDe5673511376B2","username":"test","profilePictureUrl":"default-user-image.jpg","country":"-","city":"Th
yea, that field once returned to the FE, should always have the same pattern, I.E. an url in our case, so bug fix it

2022-07-26 11:09 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/eskimo_hut_test.go
> +	testMagicToken = "WyIweGFhNTBiZTcwNzI5Y2E3MDViYTdjOGQwMDE4NWM2ZjJkYTQ3OWQwZm" +
you don't need these

2022-07-26 11:11 UTC, victor-oancea-leftclick-io commented on users/users_create.go
> +		var usrBytes []byte
why?

2022-07-26 11:12 UTC, nusanovkornilov-leftclick commented on cmd/eskimo-hut/eskimo_hut_test.go
> +	testMagicToken = "WyIweGFhNTBiZTcwNzI5Y2E3MDViYTdjOGQwMDE4NWM2ZjJkYTQ3OWQwZm" +
sure, endpoints part still in progress, will finish it today

2022-07-26 11:13 UTC, victor-oancea-leftclick-io commented on users/users_create_test.go
> +		user := bogusUser(fixture.TestingUserID(0), "").verifyUserCreated(ctx, t, testClientIP)
you have one  result, you can move it outside so we don't have the nested stuff

And also add the GIVEN as well

2022-07-26 11:13 UTC, nusanovkornilov-leftclick commented on users/users_create.go
> +		var usrBytes []byte
to get json-able error in output it is easier to parse it with regexp

2022-07-26 11:14 UTC, victor-oancea-leftclick-io commented on users/users_create_test.go
> +		_ = usersProcessor.DeleteUser(ctx, fixture.TestingUserID(0))
don't ignore any error.

Also, in users package, you can use whatever userID you want, you're not limited to those 10 ones, you can put whatever userID you want

2022-07-26 11:14 UTC, victor-oancea-leftclick-io commented on users/users_create_test.go
> +	assert.Equal(t, u.Username, user.Username)
don't do this, compare objects

2022-07-26 11:16 UTC, victor-oancea-leftclick-io commented on users/users_create.go
> +		var usrBytes []byte
we don't care about the error message, just the type

2022-07-26 11:16 UTC, victor-oancea-leftclick-io commented on users/users_create.go
> +		var usrBytes []byte
so, remove this

2022-07-26 11:17 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users_delete_test.go
> +	if len(extraHeaders) > 0 {
u don't need this if

2022-07-26 11:18 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users_delete_test.go
> +	_, status, _ := serverConnector.Delete(ctx, tb, fmt.Sprintf(`/v1w/users/%v`, userID), reqHeaders)
stop using _ !!!!

2022-08-08 17:43 UTC, merged