Device settings endpoints tests.
ice-blockchain/eskimo pull request #18
Opened 2022-07-19 17:50 UTC by antonh21

Device settings endpoints tests: CreateDeviceSettings, ModifyDeviceSettings and GetDeviceSettings.

2022-07-27 06:29 UTC, victor-oancea-leftclick-io commented on cmd/eskimo/devices_test.go
> +	repeatScenarioInParallel(t, func() {
No, we dont do that.

Remove this completely. Bad design. Tests have to be as deterministic as posible

2022-07-27 06:33 UTC, victor-oancea-leftclick-io commented on users/.testdata/application.yaml
> +      - user-device-settings-events
Nope, think again

2022-08-15 13:36 UTC, nusanovkornilov-leftclick requested changes

2022-08-15 13:36 UTC, nusanovkornilov-leftclick commented on cmd/fixture/fixture.go
> +func (*TestConnectorsBridge) MustGenerateDeviceSettingsReqBodies(
Why not to split with/without notification settings to different functions? As I can see, 90% of time u're using only one of them

2022-08-15 13:36 UTC, nusanovkornilov-leftclick commented on cmd/fixture/fixture.go
> +func (*TestConnectorsBridge) RandomHex(t *testing.T, num int) string {
Unused? Anyway you can use uuid.NewString(), do you really need variabl length?

2022-08-17 11:47 UTC, closed without merging