Postgres migration
ice-blockchain/eskimo pull request #2
Opened 2023-04-06 15:35 UTC by ice-myles

Migration from tarantool to postgres database.

2023-04-28 09:23 UTC, ice-ares requested changes

2023-04-28 09:23 UTC, ice-ares commented on users/internal/device/metadata/metadata.go
> +	sql := fmt.Sprintf(`SELECT %v FROM device_metadata WHERE user_id = $1`, selectDeviceMetadataFields())
select *

2023-04-28 09:23 UTC, ice-ares commented on users/internal/device/metadata/metadata.go
> +	sql := fmt.Sprintf(`SELECT %v FROM device_metadata WHERE user_id = $1 AND device_unique_id = $2`, selectDeviceMetadataFields())
Select *

2023-04-28 09:23 UTC, ice-ares commented on users/DDL.sql
> +                    hash_code BIGINT NOT NULL UNIQUE
Make it a serial and move it after timestamps

2023-04-28 09:23 UTC, ice-ares commented on users/DDL.sql
> +                    hidden_profile_elements text,
Move this next to client data

2023-04-28 09:23 UTC, ice-ares commented on users/DDL.sql
> +                    verified BOOLEAN NOT NULL DEFAULT FALSE,
Rename to kyc_passed

2023-04-28 09:23 UTC, ice-ares commented on users/DDL.sql
> +                         VALUES (to_timestamp(0),to_timestamp(0),'bogus','bogus','bogus','bogus','bogus','bogus.jpg','bogus',0,'bogus','RO','bogus','bogus'),
Current timestamp

2023-04-28 09:23 UTC, ice-ares commented on users/DDL.sql
> +CREATE INDEX IF NOT EXISTS users_username_ix ON users (username);
U have index on this already

2023-04-28 09:23 UTC, ice-ares commented on users/DDL.sql
> +CREATE INDEX IF NOT EXISTS users_lookup_ix ON users (username,first_name,last_name);
Remove this

2023-04-28 09:23 UTC, ice-ares commented on users/DDL.sql
> +                    user_count BIGINT NOT NULL DEFAULT 0
Move this before the other one

2023-04-28 09:23 UTC, ice-ares commented on users/DDL.sql
> +CREATE INDEX IF NOT EXISTS users_per_country_user_count_ix ON users_per_country (user_count);
Why would u need index on that?

2023-04-28 09:23 UTC, ice-ares commented on users/DDL.sql
> +CREATE INDEX IF NOT EXISTS users_referral_acquisition_history_ix ON users (referred_by, created_at);
Remove this

2023-04-28 09:23 UTC, ice-ares commented on users/DDL.sql
> +CREATE TABLE IF NOT EXISTS days (day SMALLINT primary key);
Remove this

2023-04-28 09:23 UTC, ice-ares commented on users/DDL.sql
> +                    latitude                NUMERIC,
Move all columns starting with this one until the last one, move em after timestamps

2023-04-28 09:23 UTC, ice-ares commented on users/DDL.sql
> +                    value bigint NOT NULL
Move it before the other one

2023-04-28 09:23 UTC, ice-ares commented on users/DDL.sql
> +                    primary key(user_id, device_unique_id));
With fillfactor = 70

2023-04-28 09:23 UTC, ice-ares commented on users/DDL.sql
> +                    );
With fillfactor = 70

2023-04-28 09:23 UTC, ice-ares commented on users/DDL.sql
> +                     );
With fillfactor = 70

2023-04-28 09:23 UTC, ice-ares commented on users/contract.go
> -	_   msgpack.CustomDecoder = (*NotExpired)(nil)
U would need the same thing for sql. I think the interface is sql.Scanner and something Valuer for args

2023-04-28 09:23 UTC, ice-ares commented on users/contract.go
> +var ddl string //nolint:grouper // .
Remove nolint and add a // before the group

2023-04-28 09:23 UTC, ice-ares commented on users/internal/device/metadata/metadata.go
> +func selectDeviceMetadataFields() string { //nolint:funlen // A lot of SQL fields.
Hell no

2023-04-28 09:23 UTC, ice-ares commented on users/internal/device/metadata/metadata.go
> +	return errors.Wrapf(storage.DoInTransaction(ctx, r.db, func(conn storage.QueryExecer) error {
Follow the same approach as before, cuz this is too heavy and we dont care that much about atomicity here

2023-04-28 09:23 UTC, ice-ares commented on users/top_countries.go
> +	return errors.Wrapf(storage.DoInTransaction(ctx, r.db, func(conn storage.QueryExecer) error {
Too heavy, not worth it here

2023-04-28 09:23 UTC, ice-ares commented on users/users_modify.go
> +	sql := `UPDATE users
U dont need this anymore, u can use the main update user flow to update the referred by. This was a hack for tarantool cuz replace couldnt update fields that had FK on em

2023-04-28 09:23 UTC, ice-ares commented on users/users_delete.go
> -				   u.*
Lets pls keep the * and modify the user struct if needed, with tags or pointer to stuff

2023-04-28 09:23 UTC, ice-ares commented on users/users_get.go
> +    SELECT
Select *

2023-04-28 09:23 UTC, ice-ares commented on users/users_get.go
> +		SELECT
Select *

2023-04-28 09:23 UTC, ice-ares commented on users/users_get.go
> +			SELECT
Select *

2023-05-05 15:22 UTC, ice-myles commented on users/DDL.sql
> +CREATE INDEX IF NOT EXISTS users_per_country_user_count_ix ON users_per_country (user_count);
Because this field is used at ORDER BY clause for [GetTopCountries request](https://github.com/ice-blockchain/eskimo/pull/2/files#diff-4c06fec0dd7eb91098058fc8cec7550145f2988c5b94f47fccbd5133f4831f4bR27).

2023-05-05 15:23 UTC, ice-myles commented on users/contract.go
> -	_   msgpack.CustomDecoder = (*NotExpired)(nil)
We [have already had this](https://github.com/ice-blockchain/eskimo/pull/2/files#diff-4107bc961286db59ba80aa5bb16fee3909f98505385dd6a51cf9461da04fad16R172-R235).

2023-05-05 15:25 UTC, ice-myles commented on users/DDL.sql
> +                    hash_code BIGINT NOT NULL UNIQUE
Is it enough to use SERIAL?

serial  1 to 2147483647
bigserial 1 to 9223372036854775807

2023-05-05 16:22 UTC, ice-ares commented on users/DDL.sql
> +CREATE INDEX IF NOT EXISTS users_per_country_user_count_ix ON users_per_country (user_count);
its useless, cuz it only has 250 rows, its always gonna do a full table scan anyway

2023-05-05 16:22 UTC, ice-ares commented on users/contract.go
> -	_   msgpack.CustomDecoder = (*NotExpired)(nil)
yea, but define em here

2023-05-05 16:23 UTC, ice-ares commented on users/DDL.sql
> +                    hash_code BIGINT NOT NULL UNIQUE
`bigint not null primary key generated always as identity`

2023-05-05 20:18 UTC, ice-myles commented on users/DDL.sql
> +                    hash_code BIGINT NOT NULL UNIQUE
Unique maybe? `user_id` is primary key here.

2023-05-05 22:10 UTC, ice-ares commented on users/DDL.sql
> +                    hash_code BIGINT NOT NULL UNIQUE
Right

2023-05-19 11:06 UTC, ice-ares commented on users/DDL.sql
> +-- from [country_short,elevation] -inclusive at both ends- we have ip2location information,
most likely this is no longer true

2023-05-19 11:21 UTC, ice-ares commented on users/top_countries.go
> +		INSERT INTO users_per_country (country, user_count)
u can make this logic atomic for both + & - operations with a case when then in the on conflict logic. 

I.E.

```
INSERT INTO users_per_country (country, user_count) 
VALUES ($1,1),($2,0)
ON CONFLICT (country) DO UPDATE
  SET user_count = (CASE WHEN users_per_country.country = $1 THEN GREATEST(users_per_country.user_count + 1, 0) ELSE GREATEST(users_per_country.user_count - 1, 0) END)
```

2023-05-19 11:29 UTC, ice-ares commented on users/users_get.go
> +                  JOIN USERS t0
do yo need to join those again?

2023-05-19 14:38 UTC, ice-cronus commented on users/users_get.go
> +                  JOIN USERS t0
Fixed, that's for ordering but we can get values from subquery

2023-05-19 14:39 UTC, ice-cronus commented on users/top_countries.go
> +		INSERT INTO users_per_country (country, user_count)
We have to build sql dynamically to do so ( cuz only increment or only decrement are possible as well), but I redone that

2023-05-19 14:39 UTC, ice-cronus commented on users/DDL.sql
> +-- from [country_short,elevation] -inclusive at both ends- we have ip2location information,
removed

2023-05-21 19:17 UTC, merged