Feature/initial implementation
ICE-Blockchain/eskimo pull request #2
Opened 2022-04-12 07:39 UTC by kfedor

Initial implementation of eskimo

2022-04-12 07:48 UTC, victor-oancea-leftclick-io commented on users/fixture/contract.go
> +	User struct {
u can use the same struct from users/contract.go. There's no need for this

2022-04-12 11:36 UTC, victor-oancea-leftclick-io commented on users/DDL.lua
>                      referredBy STRING REFERENCES users(id) ON DELETE SET NULL,
lets rename this to referred_by

2022-04-12 11:36 UTC, victor-oancea-leftclick-io commented on users/contract.go
> +	DDL string
ddl

2022-04-12 11:38 UTC, victor-oancea-leftclick-io commented on users/users.go
> +	u.ID = fmt.Sprintf("%v%v", u.ID, uuid.New().String())
nope, we don't generate uuid, we use u.ID directly

2022-04-12 11:38 UTC, victor-oancea-leftclick-io commented on users/users.go
> +	if err := u.db.GetTyped("USERS", nil, []interface{}{id}, result); err != nil {
pk_unnamed_USERS

2022-04-12 11:39 UTC, victor-oancea-leftclick-io commented on users/users.go
> +
too many useless spaces

2022-04-12 11:40 UTC, victor-oancea-leftclick-io commented on users/users.go
> +	sql := `UPDATE users SET EMAIL = :email, FULL_NAME = :fullName, PHONE_NUMBER = :phoneNumber, USERNAME = :username, PROFILE_PICTURE = :profilePictureURL, UPDATED_AT = :updatedAt WHERE ID = :id`
wrong, this is a patch. A patch modifies ONLY what's provided in the body. Everything else is untouched

2022-04-12 11:42 UTC, victor-oancea-leftclick-io commented on users/users.go
> +	sql := `UPDATE users SET EMAIL = :email, FULL_NAME = :fullName, PHONE_NUMBER = :phoneNumber, USERNAME = :username, PROFILE_PICTURE = :profilePictureURL, UPDATED_AT = :updatedAt WHERE ID = :id`
what you implemented is a PUT, which would be a full update

2022-04-12 11:43 UTC, victor-oancea-leftclick-io commented on users/users.go
> +		DeletedAt:         time.Unix(0, u.DeletedAt).UTC(),
nil, deletedAt is set only when deleting it

2022-04-12 11:44 UTC, victor-oancea-leftclick-io commented on users/users.go
> +		"profilePictureURL": user.ProfilePictureURL,
we need to default to something here

2022-04-12 11:44 UTC, victor-oancea-leftclick-io commented on users/users.go
> +		"referredBy":        refer,
u can use `*UserID` instead of `interface{}`

2022-04-12 11:46 UTC, victor-oancea-leftclick-io commented on users/users.go
> +	}
else {

get a random one from db
}

2022-04-12 11:46 UTC, victor-oancea-leftclick-io commented on users/users.go
> +		"referredBy":        refer,
actually, you only need `UserID` cuz its not nullable

2022-04-12 11:47 UTC, victor-oancea-leftclick-io commented on users/users.go
> +
too many useless spaces

2022-04-12 11:48 UTC, victor-oancea-leftclick-io commented on users/contract.go
> +		DeletedAt         time.Time `json:"deletedAt,omitempty" example:"2022-01-03T16:20:52.156534Z"`
this should be `*time.Time` like it was before

2022-04-12 11:50 UTC, victor-oancea-leftclick-io commented on users/users.go
> +		return err
wrap it

2022-04-12 11:51 UTC, victor-oancea-leftclick-io commented on users/users.go
> +	if err := u.db.GetTyped("USERS", nil, []interface{}{id}, result); err != nil {
tarantool.StringKey{S:id}

2022-04-12 11:52 UTC, victor-oancea-leftclick-io commented on users/users.go
> +	query, err := u.db.PrepareExecute(sql, params)
pick a pattern and stick to it for all of them:

query, err := u.db.PrepareExecute(sql, params)
if err := storage.CheckSQLDMLErr(query, err); err != nil {}

or 

if err := storage.CheckSQLDMLErr(u.db.PrepareExecute(sql, params)); err != nil {}

2022-04-12 11:53 UTC, victor-oancea-leftclick-io commented on users/users.go
> -// SPDX-License-Identifier: BUSL-1.1
why did u do that?

2022-04-12 13:26 UTC, victor-oancea-leftclick-io commented on cmd/eskimo/users.go
> +	return server.RequiredStrings(map[string]string{"username": req.Username})
is not required.


what is required is to have at least 1 field not empty, that's what I meant

2022-04-12 13:28 UTC, victor-oancea-leftclick-io commented on cmd/eskimo/users.go
> +	eval := regexp.MustCompile(`^[a-zA-Z][a-zA-Z\d_-]+$`)
the logic is : `4-20 alphanumeric chars or . - _`

2022-04-12 13:30 UTC, victor-oancea-leftclick-io commented on cmd/eskimo/users.go
> +	// What do you mean? We are in RequestValidateUsername
what you did above, to validate the structure of the username

2022-04-12 20:03 UTC, kfedor commented on cmd/eskimo/users.go
> +	eval := regexp.MustCompile(`^[a-zA-Z][a-zA-Z\d_-]+$`)
can a username start with a digit?

2022-04-13 07:28 UTC, victor-oancea-leftclick-io commented on cmd/eskimo/users.go
> +	eval := regexp.MustCompile(`^[a-zA-Z][a-zA-Z\d_-]+$`)
Yep, the order of the chars is irrelevant

2022-04-13 08:39 UTC, kfedor commented on users/users.go
> +	}
What about first insertion?

2022-04-13 08:43 UTC, victor-oancea-leftclick-io commented on users/users.go
> +	}
the referral is inserted only in the AddUser (POST endpoint)

If you have it in the request body, you use it, otherwise you get a random one from db and use that instead

2022-04-13 12:27 UTC, kfedor commented on users/contract.go
> +	UserID string
I didn't get this :(

2022-04-13 12:29 UTC, victor-oancea-leftclick-io commented on users/contract.go
> +	UserID string
use `UserID = string` 
instead of `UserID string` 

There's a big difference.

2022-04-13 12:29 UTC, kfedor commented on users/users.go
> +	}
but if DB is empty and column is not null I can't insert anything

2022-04-13 12:29 UTC, kfedor commented on users/users.go
> +				VALUES(:id, :email, :fullName, :phoneNumber, :username, :referredBy, :profilePictureURL, :createdAt)`
the same as createdAt ?

2022-04-13 12:33 UTC, victor-oancea-leftclick-io commented on users/users.go
> +				VALUES(:id, :email, :fullName, :phoneNumber, :username, :referredBy, :profilePictureURL, :createdAt)`
yep

2022-04-13 12:33 UTC, victor-oancea-leftclick-io commented on users/users.go
> +	}
we're gonna have a `genesis` entry which will point to itself

2022-04-13 12:35 UTC, kfedor commented on cmd/eskimo/users.go
> +	eval := regexp.MustCompile(`^[a-zA-Z][a-zA-Z\d_-]+$`)
I think we should exclude usernames like "....", "-_-_", "1111"
isn't it?

2022-04-13 12:39 UTC, victor-oancea-leftclick-io commented on cmd/eskimo/users.go
> +	eval := regexp.MustCompile(`^[a-zA-Z][a-zA-Z\d_-]+$`)
we can easily change that at a later point, so don't worry

2022-04-13 15:33 UTC, kfedor commented on users/users.go
> +	}
What is a genesis entry? How I can create it?
Can we use it as default referrer instead of random one?

2022-04-13 15:36 UTC, victor-oancea-leftclick-io commented on users/users.go
> +	}
we're gonna manually create an entry in the database, that has referred_by = id

2022-04-13 15:36 UTC, victor-oancea-leftclick-io commented on users/users.go
> +	}
nope, we need a random one

2022-04-13 15:40 UTC, kfedor commented on users/users.go
> +	}
but how to create an entry despite foreign key restrictions?

2022-04-23 15:16 UTC, victor-oancea-leftclick-io requested changes

2022-04-23 15:16 UTC, victor-oancea-leftclick-io commented on users/users.go
> +	_, err = req.
Whats the response of the api?

2022-04-23 15:16 UTC, victor-oancea-leftclick-io commented on users/users.go
> +	if u.PhoneNumber != "" {
There's another flow for modifying the phone number

2022-04-23 15:16 UTC, victor-oancea-leftclick-io commented on users/users.go
> +		return err
Wrap it

2022-04-23 15:16 UTC, victor-oancea-leftclick-io commented on users/DDL.lua
>                      profile_picture STRING NOT NULL,
Lets pls rename this (& the db struct field) to profile picture name

2022-04-23 15:16 UTC, victor-oancea-leftclick-io commented on users/users.go
> +	var refer UserID
Do this via sql only:

Insert into .... values (..., (select ...))

2022-04-23 15:16 UTC, victor-oancea-leftclick-io commented on users/users.go
> +	if id == "" {
U wont need this after you fix getting the random referral via sql

2022-04-23 15:16 UTC, victor-oancea-leftclick-io commented on users/users.go
> +func (u *User) GenSQLUpdate() (sql string, params map[string]interface{}) {
Make it private. Make sure everything that is meant to be privite, is lowercased

2022-04-23 15:16 UTC, victor-oancea-leftclick-io commented on users/users.go
>  package users
Also, i'd extract logic from here into separate files as this one has 400 lines and will grow even more

I'd recommend 1 file for usecase or endpoint

2022-04-24 19:53 UTC, kfedor commented on application.yaml
> +    retryCount: 3
3 enough?

2022-04-24 19:56 UTC, kfedor commented on cmd/eskimo-hut/api/docs.go
> -                        "description": "Request params",
seems like make did it
I'll fix

2022-04-24 20:05 UTC, kfedor commented on users/users.go
> +		return err
return errors.Wrapf(err,"unable to get user %v", userID)

2022-04-24 20:09 UTC, kfedor commented on application.yaml
> +cmd/eskimo-hut:
removed

2022-04-24 20:09 UTC, kfedor commented on application.yaml
> +    consumerGroup: eskimo-users
renamed

2022-04-24 20:12 UTC, kfedor commented on application.yaml
> +    zoneName: ice-staging
urlUpload: https://storage.bunnycdn.com/ice-staging/profile
    urlDownload: https://ice-staging.b-cdn.net/profile

2022-04-24 20:20 UTC, kfedor commented on cmd/eskimo-hut/users.go
> +		ProfilePictureURL: defaultUserImage,
Do you mean ProfilePictureURL: users.DefaultUserImage ?

2022-04-24 20:21 UTC, kfedor commented on cmd/eskimo-hut/users.go
>  	return server.OK(req)
return server.OK()

2022-04-24 20:22 UTC, kfedor commented on cmd/eskimo-hut/users.go
>  	return server.OK(req)
return server.OK()

2022-04-24 20:22 UTC, kfedor commented on cmd/eskimo-hut/users.go
> +				return errors.Wrap(err, "bind failed")
return errors.Wrap(err, "FormMultipart binding failed")

2022-04-24 20:23 UTC, kfedor commented on cmd/eskimo/contract.go
> +const userNotFoundCode = "USER_NOT_FOUND"
moved

2022-04-24 20:25 UTC, kfedor commented on users/contract.go
> +		HashCode uint64 `json:"hash_code"`
HashCode uint64 `json:"hashCode"`

2022-04-24 20:27 UTC, kfedor commented on users/users.go
> +func (u *User) GenSQLUpdate() (sql string, params map[string]interface{}) {
func (u *User) genSQLUpdate() (sql string, params map[string]interface{})

2022-04-24 20:28 UTC, kfedor commented on users/users.go
>  package users
users_add, users_get, users_remove, users_modify ?

2022-04-24 21:16 UTC, victor-oancea-leftclick-io commented on application.yaml
> +    retryCount: 3
For now yes, we'll tweak it later on

2022-04-24 21:17 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users.go
> +		ProfilePictureURL: defaultUserImage,
Nope, the logic should be handled in add users

2022-04-24 21:19 UTC, victor-oancea-leftclick-io commented on users/users.go
>  package users
something like that, yea

2022-04-24 21:20 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/api/docs.go
> -                        "description": "Request params",
Make did it based on the changes u made to the swagger comments

2022-04-25 11:35 UTC, kfedor commented on users/users.go
> +	var refer UserID
done

2022-04-25 12:12 UTC, kfedor commented on cmd/eskimo-hut/eskimo_hut.go
> +	s.usersRepository = users.New(ctx, cancel)
Repository for eskimo, Processor for eskimo-hut, right?
Both use database and message broker?
Are any difference between them?

2022-04-25 12:15 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/eskimo_hut.go
> +	s.usersRepository = users.New(ctx, cancel)
Processor has a repository.

Eskimo will use the read only operations from the repository. No message broker interactions here

Eskimo-hut will use the write only operations from the repository (+read only ones maybe for testing) & the message broker for consuming and producing.

2022-04-25 12:38 UTC, kfedor commented on users/DDL.lua
> +                    deleted_at UNSIGNED
Should we return DeletedAt on delete to user or remove field completely and just return 200?

2022-04-25 13:03 UTC, kfedor commented on users/contract.go
> +		} `yaml:"storage"`
pictureStorage

2022-04-25 13:04 UTC, kfedor commented on users/users.go
> +func (u *users) UploadProfilePicture(_ context.Context, data *multipart.FileHeader) error {
func (u *users) uploadProfilePicture(_ context.Context, data *multipart.FileHeader) error {

2022-04-25 14:14 UTC, kfedor commented on users/users.go
> +	_, err = req.
HTTP/2 200 
content-length: 0
date: Mon, 25 Apr 2022 14:12:22 GMT

2022-04-25 14:15 UTC, victor-oancea-leftclick-io commented on users/users.go
> +	_, err = req.
ok

2022-04-25 14:19 UTC, kfedor commented on users/users.go
> +func (u *users) UploadProfilePicture(_ context.Context, data *multipart.FileHeader) error {
req.SetContext(ctx)

2022-04-25 14:24 UTC, victor-oancea-leftclick-io commented on users/users.go
> +func (u *users) UploadProfilePicture(_ context.Context, data *multipart.FileHeader) error {
then use a new client instance injected into users struct, rather than using that global singleton

2022-04-25 14:34 UTC, kfedor commented on cmd/eskimo-hut/users.go
> +				}.Fail(errors.Wrapf(err, err.Error())),
msg := fmt.Sprintf("user with id `%v` already exists.", resp.ID)

2022-04-25 14:36 UTC, kfedor commented on cmd/eskimo-hut/eskimo_hut.go
> +	s.usersRepository = users.New(ctx, cancel)
don't send message on user creation?

2022-04-25 15:12 UTC, kfedor commented on cmd/eskimo-hut/user_validations.go
> -	//TODO implement me
Can I modify GetUser to accept index as a parameter to be able to request by different columns? 
like GetUser(ctx context.Context, val string, index string) 

Also we need new index on Username
CREATE INDEX IF NOT EXISTS users_username_ix ON users (username);

2022-04-26 07:09 UTC, kfedor commented on users/users.go
> +	if u.PhoneNumber != "" {
let it be when developing the validation of the number?

2022-04-26 07:15 UTC, victor-oancea-leftclick-io commented on users/users.go
> +	if u.PhoneNumber != "" {
Yep

2022-04-26 12:10 UTC, victor-oancea-leftclick-io commented on Makefile
> +checkGenerated: generate addLicense
git fetch
git rebase origin/master
git push

2022-04-26 12:11 UTC, victor-oancea-leftclick-io commented on application.yaml
> +    port: 443
1443

2022-04-26 12:14 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/eskimo_hut.go
> +		},
call fail(err)

2022-04-26 12:14 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/eskimo_hut.go
> +func getServerErrorResponse(httpCode int, msg, code string) server.Response {
httpCode int, err error, code string

2022-04-26 12:16 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/user_validations.go
> +	if len(req.Username) < 4 || len(req.Username) > 20 || eval.MatchString(req.Username) == false {
the structural validation happens in the validate method

2022-04-26 12:18 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/user_validations.go
>  	return server.OK(req)
OK()

2022-04-26 12:19 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users.go
> +			msg := fmt.Sprintf("user with id `%v` already exists.", resp.ID)
not really. It can also be username

2022-04-26 12:22 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users.go
> +			msg = fmt.Sprintf("user with id `%v` already exists.", req.ID)
you can't change the id, but u can change the username

2022-04-26 12:23 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users.go
> +			msg = fmt.Sprintf("unable to modify user `%v`: %v.", req, err.Error())
you don't need to include the request body

2022-04-26 12:27 UTC, victor-oancea-leftclick-io commented on cmd/eskimo/contract.go
> +		readRepository users.ReadRepository
usersReadRepository

2022-04-26 12:30 UTC, victor-oancea-leftclick-io commented on cmd/eskimo/users.go
> +		Username:          resp.Username,
and ID

2022-04-26 12:32 UTC, victor-oancea-leftclick-io commented on users/contract.go
> -// Private API.
this comment is important. Don't lose it. Add it before the private const declaration

2022-04-26 12:32 UTC, victor-oancea-leftclick-io commented on users/contract.go
> +		ReadRepository
u don't need this

2022-04-26 12:33 UTC, victor-oancea-leftclick-io commented on users/contract.go
> +		ReadRepository
you don't need either of these 2 repositories here

2022-04-26 12:33 UTC, victor-oancea-leftclick-io commented on users/contract.go
> +func (u *users) Close() error {
implement this and move it out of this file

2022-04-26 12:35 UTC, victor-oancea-leftclick-io commented on users/contract.go
> +func (u *users) Close() error {
actually, you don't need this

2022-04-26 12:38 UTC, victor-oancea-leftclick-io commented on users/users.go
> +	log.Info("closing db connection...")
wrong logging. Move it inside the func

2022-04-26 12:38 UTC, victor-oancea-leftclick-io commented on users/users.go
> +		return errors.Wrap(err, "closing users repository failed")
returning the first err is enough

2022-04-26 12:51 UTC, victor-oancea-leftclick-io commented on users/users_add.go
> +	var refer UserID
var referral string
 	if user.ReferredBy != "" {
 		referral = ":referredBy"
 	} else {
 		referral = `(SELECT ID FROM users ORDER BY random() LIMIT 1)`
 	}

2022-04-26 12:52 UTC, victor-oancea-leftclick-io commented on users/users_add.go
> +
if user.ReferredBy != "" {
 		params["referredBy"] = user.ReferredBy
 	}

2022-04-26 12:53 UTC, victor-oancea-leftclick-io commented on users/users_add.go
> +	return nil
return errors.Wrap(u.sendUsersMessage(ctx, user), "failed to send user created message")

2022-04-26 12:57 UTC, victor-oancea-leftclick-io commented on users/users_delete.go
> +	return nil
return errors.Wrap(u.sendUsersMessage(ctx, gUser.deleted()), "failed to send deleted user message")

2022-04-26 12:59 UTC, victor-oancea-leftclick-io commented on users/users_get.go
> +	return false, nil
return result.ID != "", nil

2022-04-26 13:01 UTC, victor-oancea-leftclick-io commented on users/users_modify.go
> +	if u.PhoneNumber != "" {
remove this if

2022-04-26 13:04 UTC, victor-oancea-leftclick-io commented on users/users_modify.go
> +	defer file.Close()
log error

2022-04-26 13:09 UTC, victor-oancea-leftclick-io commented
also, @kfedor pls change the coverage % from 60 to 0

2022-04-26 14:38 UTC, kfedor commented on cmd/eskimo-hut/users.go
> +			msg = fmt.Sprintf("unable to modify user `%v`: %v.", req, err.Error())
I'll use errors from users

2022-04-26 14:39 UTC, kfedor commented on cmd/eskimo/users.go
> +		Username:          resp.Username,
added

2022-04-26 14:52 UTC, kfedor commented on users/users_add.go
> +	var refer UserID
I tried using SQL request as a param to PrepareExecute() and failed

2022-04-26 14:54 UTC, kfedor commented on application.yaml
> +    port: 443
eskimo-hut 1443

2022-04-26 15:14 UTC, kfedor commented on users/users_add.go
> +
ah ok

2022-04-26 15:38 UTC, victor-oancea-leftclick-io commented on users/contract.go
> +		ReadRepository
i was wrong, you need them

2022-04-26 15:38 UTC, victor-oancea-leftclick-io commented on users/contract.go
> +		ReadRepository
i was wrong, you need them

2022-04-26 15:54 UTC, victor-oancea-leftclick-io commented on users/users_modify.go
> +	defer file.Close()
the error from file Close is ignored

2022-04-26 19:30 UTC, kfedor commented on users/users_modify.go
> +	defer file.Close()
`defer func(file multipart.File) {
		err = file.Close()
		if err != nil {
			log.Error(err, "error closing file")
		}
	}(file)`

2022-04-26 21:10 UTC, victor-oancea-leftclick-io requested changes
@kfedor Good job, you're almost there! Just a few more to go

2022-04-26 21:10 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users.go
> +			httpCode = http.StatusBadRequest
default would be 500

2022-04-26 21:10 UTC, victor-oancea-leftclick-io commented on cmd/eskimo/users.go
> +		}
else return unexpected

2022-04-26 21:10 UTC, victor-oancea-leftclick-io commented on users/users.go
> +func (u *users) Close() error {
i think you need to create 2 close receiver methods, one for repository one for processor, and implement them like in jazmine for example

2022-04-27 06:38 UTC, kfedor commented on cmd/eskimo-hut/user_validations.go
> +		return getServerErrorResponse(http.StatusBadRequest, err, userBadRequest)
const StatusBadRequest int = 400
// @Failure      400            {object}  server.ErrorResponse  "if validations fail"

is this wrong?

2022-04-27 06:49 UTC, kfedor commented on cmd/eskimo-hut/users.go
> +			httpCode = http.StatusBadRequest
httpCode = http.StatusInternalServerError

2022-04-27 06:52 UTC, kfedor commented on cmd/eskimo-hut/user_validations.go
> +		return getServerErrorResponse(http.StatusBadRequest, err, userBadRequest)
ok 
return getServerErrorResponse(http.StatusInternalServerError, err, userBadRequest)

2022-04-27 07:17 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/user_validations.go
> +		return getServerErrorResponse(http.StatusBadRequest, err, userBadRequest)
That error is cuz db call failed

2022-04-27 08:25 UTC, victor-oancea-leftclick-io submitted a review, later dismissed
You still have some issues with the repository, you rolled back good changes for some reason, but we'll fix them in other PRs

2022-04-27 08:51 UTC, victor-oancea-leftclick-io approved these changes

2022-04-27 11:11 UTC, antonh21 approved these changes

2022-04-27 11:11 UTC, merged