user modification tests
ice-blockchain/eskimo pull request #23
Opened 2022-08-08 15:40 UTC by ice-cronus

Implemented for internal (./users) part and for cmd (eskimo-hut)

2022-08-11 11:05 UTC, antonh21 requested changes

2022-08-11 11:05 UTC, antonh21 commented on users/users_modify_test.go
> +
We need to add `ModifyUser` tests for next cases:
- When we trying to update the user that doesn't exist in the database.
- When sqlUpdate() returns only 2 fields (it returns nil):
```
sql, params := usr.genSQLUpdate(ctx)
	if len(params) == 1+1 {
		return nil
	}
```
- And this updated stuff with profile picture maybe (if that separate business (did't understand while)).
- ContextTimeout (but @victor-oancea-leftclick-io didn't add this case to his tests, why?)
- Phone validation as I understand will be checked at the separate test file.

2022-08-11 11:15 UTC, nusanovkornilov-leftclick commented on cmd/eskimo-hut/users_modify_test.go
> +func TestService_ModifyUser_Success_ChangeCountryAndCity(t *testing.T) {
hmm, they are separated cuz they recalculates user-per-country counters, but that's significant for internal tests ( we're checking message broker there, but for cmd tests I think we can unite them, you're right

2022-08-11 11:16 UTC, nusanovkornilov-leftclick commented on cmd/fixture/fixture.go
> +		if len(reqBody) == 2 && reqBody["phoneNumber"] != nil && reqBody["phoneNumberHash"] != nil {
because of map is map[string]interface{}, it has nil zero value

2022-08-11 11:20 UTC, nusanovkornilov-leftclick commented on cmd/fixture/fixture.go
> +	assert.Equal(tb, 200, resp.StatusCode) //nolint:gomnd // That's not a magic number.
That's a picture. Actually we can get data and check it's hash to verify if it matches with the source picture. Will do that.

2022-08-11 11:23 UTC, antonh21 commented on cmd/fixture/fixture.go
> +	assert.Equal(tb, 200, resp.StatusCode) //nolint:gomnd // That's not a magic number.
Nice idea 👍

2022-08-11 12:23 UTC, antonh21 requested changes

2022-08-11 12:23 UTC, antonh21 commented on users/phone_number_test.go
> +func TestUserProcessor_ValidatePhoneNumber_Success_FullCycleOnUserModification(t *testing.T) {
Interesting, does twilio have any restrictions for the codes entering?
I mean what will be if I will enter 100 times wrong code? And if 1000 times?
Or the twilio service will mark our account as spam in this case and will block? :-))

Though this is more twilio testing than our code.

2022-08-11 12:23 UTC, antonh21 commented on users/phone_number_test.go
> +			assert.True(t, err != nil && errors.Is(err, ErrInvalidPhoneValidationCode))
```
require.Error(t, err)
assert.True(t, errors.Is(err, ErrInvalidPhoneValidationCode))
```
is better I think.

2022-08-11 12:23 UTC, antonh21 commented on users/phone_number_test.go
> +			assert.True(t, err != nil && errors.Is(err, ErrNotFound))
```
require.Error(t, err)
assert.True(t, errors.Is(err, ErrNotFound))
expected := fmt.Sprintf("user  with id %v has no phone number waiting for confirmation", user.PhoneNumber)
assert.Contains(t, error.Error(),  expected)
```

2022-08-11 12:23 UTC, antonh21 commented on users/phone_number_test.go
> +			assert.True(t, err != nil && errors.Is(err, ErrNotFound))
```
require.Error(t, err)
assert.True(t, errors.Is(err, ErrNotFound))
expected := fmt.Sprintf("no phone number %v waiting for confirmation", user.PhoneNumber)
assert.Contains(t, error.Error(),  expected)
```
to make this case fully checked (the same we can do for last 3d case with ErrNotFound):
```
phone number hash %v does not match initial hash
```

2022-08-11 12:23 UTC, antonh21 commented on users/phone_number_test.go
> +
- `ErrExpiredPhoneValidationCode` should be checked here or at cmd (or even both) - as described at `cmd` `./testdata/application.yaml` can be changed a bit not to wait too much.
- when validation is okay, but `modifyPhoneNumber` breaks in the flow (if it possible, otherwise at least by unit-tests).
- when replacePhoneValidation breaks in the flow.
If we can't check the last, maybe it worths to add unit-test for this separately.

2022-08-11 17:12 UTC, victor-oancea-leftclick-io commented on cmd/fixture/fixture.go
> +	assert.Equal(tb, 200, resp.StatusCode) //nolint:gomnd // That's not a magic number.
Not that nice, cuz the picture is compressed and optimized after you store it, its not the same byte stream

2022-08-11 17:15 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/user_validations_test.go
> +		assert.Equal(t, 200, status)
Indirectly yes. But modify can never be a given. You generate the state with create

2022-08-11 17:17 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/user_validations_test.go
> +	for fieldName, reqBody := range missingFieldsBodies() {
Yep

2022-08-11 17:19 UTC, victor-oancea-leftclick-io commented on users/phone_number_test.go
> +			assert.True(t, err != nil && errors.Is(err, ErrInvalidPhoneValidationCode))
Require error
Assert ErrorIs

2022-08-12 09:53 UTC, nusanovkornilov-leftclick commented on users/phone_number_test.go
> +
modifyPhoneNumber is checked in FullCycle test, here, user phone number is modified: "updates user with phone number into database"
 replacePhoneValidation is also checked on full cycle, with replacement and marking code as expired "updates phone validation as expired (validation code = userID)"

But it seems there is one more point for replacePhoneValidation when user has existing validation and then changes number one more time, will try to handle it

2022-08-12 12:03 UTC, victor-oancea-leftclick-io requested changes

2022-08-12 12:03 UTC, victor-oancea-leftclick-io commented on users/users_modify_test.go
> +		AgendaPhoneNumberHashes: uuid.NewString(),
and phone number, arg or default

2022-08-12 19:38 UTC, antonh21 commented on cmd/fixture/fixture.go
> +		assert.Equal(tb, body, getBodyAfter[:strings.LastIndex(getBodyAfter, ",\"referralCount\":")]+"}")
It's the solution of the problem when you modify an user and this user has already had referrals. In this case `GetUser` returns user information + `ReferralCount` field with the number of the referrals.

2022-08-15 11:16 UTC, nusanovkornilov-leftclick commented on cmd/fixture/fixture.go
> +		assert.Equal(tb, body, getBodyAfter[:strings.LastIndex(getBodyAfter, ",\"referralCount\":")]+"}")
It is the same as you implemented create user response validation. Cause is that referralCount not omits empty value on latest master

2022-08-15 11:20 UTC, nusanovkornilov-leftclick commented on cmd/eskimo-hut/users_modify_test.go
> +			"profilePicture": bytes.NewBuffer(profilePicture),
Yep, I am using field name for filename in this case, so you're right, we're losing an extension part, but I am not sure if it is really required for testing. Otherwise I can find two different approaches: 
1) tmp file (but we'll need to write our in-memory data to it and handle open/close)
2) some in-memory filesystem (I see there are some libs for that), but we still need to setup it, and it looks like overkill for such simple task

2022-08-15 11:30 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users_modify_test.go
> +			"profilePicture": bytes.NewBuffer(profilePicture),
```
// content holds our static web server content.
//go:embed image/* template/*
//go:embed html/index.html
var content embed.FS
```

2022-08-15 11:31 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/users_modify_test.go
> +			"profilePicture": bytes.NewBuffer(profilePicture),
https://pkg.go.dev/embed

2022-08-15 13:27 UTC, nusanovkornilov-leftclick commented on users/phone_number_test.go
> +			assert.True(t, err != nil && errors.Is(err, ErrNotFound))
added text validation as well, but victor said before that we're not interested in error message, only in code

2022-08-15 13:43 UTC, nusanovkornilov-leftclick commented on users/users_modify_test.go
> +
added tests mentioned above, profile picture is covererd by cmd part because of multipart in function's signature

2022-08-16 10:08 UTC, victor-oancea-leftclick-io requested changes

2022-08-16 10:08 UTC, victor-oancea-leftclick-io commented on cmd/fixture/fixture.go
> +// We need to keep this public as other requsts can be created outside of fixture-package (we're keep only create / delete get here).
Remove comment, it's obvious

2022-08-16 10:08 UTC, victor-oancea-leftclick-io commented on users/fixture/contract.go
> +	SMSFixture interface {
You dont need this, its complicating the testing code, just make the client every time for each method

2022-08-16 11:51 UTC, nusanovkornilov-leftclick commented on cmd/eskimo-hut/user_validations_test.go
> +	WHEN("we're getting user information after phone number update", func() {
it is validated in api method as well, with
`assert.Equal(tb, body (response of /user-validations/%v/phone-number), getBodyAfter (read user's state after confirmation))`

So if this usecase is useless ( cuz we're validating field values above with body) - I'll remove it

2022-08-16 13:49 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/user_validations_test.go
> +	WHEN("we're getting user information after phone number update", func() {
then its duplicated, so yea, remove it

2022-08-17 11:47 UTC, closed without merging