Device settings create/modify/get endpoints tests.
ice-blockchain/eskimo pull request #29
Opened 2022-08-17 14:18 UTC by ice-myles

2022-08-22 13:40 UTC, ice-ares requested changes
Explicitly define/assert/expect stuff; encapsulation is bad for tests (unless u're using it for side effects)

2022-08-22 13:40 UTC, ice-ares commented on cmd/eskimo-hut/devices_test.go
> +	var reqBody, body string
Move them as close as possible from where they're used

2022-08-22 13:40 UTC, ice-ares commented on cmd/eskimo-hut/devices_test.go
> +			bridge.AssertCreatedOrModifiedDeviceSettingsResponseBody(t, &expected, body)
Should not be 1:1 there, so follow the same pattern as with create users: explicitly define what you set in the req  body and explicitly define what u expect in the response, which is at least what u set in the req body, but not always the same

2022-08-22 13:40 UTC, ice-ares commented on cmd/eskimo-hut/devices_test.go
> +// SPDX-License-Identifier: BUSL-1.1
Split file into 1 separate file for each endpoint

2022-08-22 13:40 UTC, ice-ares commented on cmd/eskimo/devices_test.go
> +
Separate into 1 file for each endpoint

2023-01-13 17:36 UTC, ice-myles commented
Was rebased into the `feature/fixing-tests` branch. Will continue from that branch.

2023-01-13 17:36 UTC, closed without merging