users/get tests
ice-blockchain/eskimo pull request #31
Opened 2022-08-18 11:34 UTC by ice-laius

2022-08-18 12:07 UTC, ice-myles requested changes

2022-08-18 12:07 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +			assert.Equal(t, user.Username, "bogus.user")
Let's try to compare bodies.

2022-08-18 12:07 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +		bridge.CreateUser(ctx, t, userID, token, reqBody)
Is it possible to use `bridge.MustCreateDefaultUser` function for such user creation?

2022-08-18 12:07 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +
You need to add at least testcase when username is not valid for `GetUserByUsername`.
See `cmd/eskimo/users.go:107`
`if !users.CompiledUsernameRegex.MatchString(req.Data.Username) {`

2022-08-18 12:07 UTC, ice-myles commented on users/users_get_test.go
> +			assert.Equal(t, res.Username, "username0")
This is not enough to check only username, you should check all outcome.

2022-08-18 12:07 UTC, ice-myles commented on users/users_get_test.go
> +			require.Error(t, err)
How about to check what error was returned here?
```
err.Error()
```

2022-08-18 12:07 UTC, ice-myles commented on users/users_get_test.go
> +			assert.Equal(t, res.Username, "username1")
The same: you need to check all outcome, not only 1 field.

2022-08-18 14:33 UTC, ice-laius commented on users/users_get_test.go
> +		assert.Equal(tb, val.Username, newUser.Username)
we don't have last_mining, last_ping there

2022-08-18 14:44 UTC, ice-myles commented on users/users_get_test.go
> +		assert.Equal(tb, val.Username, newUser.Username)
The `GetUsers` SQL starts from this:
```
SELECT u.last_mining_started_at                                                                          AS last_mining_started_at,
				   (CASE
						WHEN t0.id = user_requesting_this.id OR u.id = user_requesting_this.referred_by
							THEN u.last_ping_at
						ELSE null
					END)                                                                                             AS last_ping_at,	
```
And you use `verifyUser` for `GetUsers` test.

2022-08-18 19:44 UTC, ice-laius commented on users/users_get_test.go
> +func TestRepository_GetUserByUsername_Success(t *testing.T) { //nolint:paralleltest // We need a clean database.
ok

2022-08-18 19:57 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +
? this is not create
we dont check username for get

2022-08-19 07:59 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +
No, this is the `GetUserByName` endpoint.

2022-08-19 08:27 UTC, ice-laius commented on users/users_get_test.go
> +		assert.Equal(tb, val.Username, newUser.Username)
done

2022-08-19 08:29 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +
I see, in cmd

2022-08-19 08:29 UTC, ice-laius commented on users/users_get_test.go
> +			assert.Equal(t, res.Username, "username0")
done

2022-08-19 08:29 UTC, ice-laius commented on users/users_get_test.go
> +			assert.Equal(t, res.Username, "username1")
done

2022-08-19 12:53 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +
done

2022-08-19 13:01 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +			assert.Equal(t, gjson.Get(body, "code").String(), "INVALID_USERNAME")
Check please [here](https://github.com/ice-blockchain/eskimo/blob/master/cmd/eskimo-hut/users_create_test.go#L227-L228) how this is validated to make it in the similar way through all the tests.

2022-08-19 13:12 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +			assert.Equal(t, gjson.Get(body, "code").String(), "INVALID_USERNAME")
done

2022-08-19 13:19 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +		IT("is successfully returned", func() {
Wrong description.

2022-08-19 13:22 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +func TestService_GetUserByUsername_Failure_RegExp(t *testing.T) {
Let's rename this test name to something decent. We check if username is not valid. Maybe `_WithInvalidUsername`?

2022-08-19 13:23 UTC, ice-laius commented on users/users_get_test.go
> +	ctx = context.WithValue(ctx, "requestingUserIDCtxValueKey", "userid0") //nolint:staticcheck // No way
this is TestRepository_GetUsers_Success_EmptyDB

2022-08-19 13:24 UTC, ice-laius commented on users/users_get_test.go
> +func TestRepository_GetUsers_Success_EmptyDB(t *testing.T) { //nolint:paralleltest // We need a clean database.
limits are limits, empty db is another
why doing so?

2022-08-19 13:26 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +	WHEN("get user by ID", func() {
by Username.

2022-08-19 13:28 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +			assert.Equal(t, 400, status)
Let's move status check into the separate `IT()` as it is done for other tests to make all similar to each other. As example [here](https://github.com/ice-blockchain/eskimo/blob/master/cmd/eskimo-hut/users_create_test.go#L277-L279)

2022-08-19 13:30 UTC, ice-myles commented on cmd/fixture/fixture.go
> +func (b *TestConnectorsBridge) MustCreateAllAvailableUsers(ctx context.Context, tb testing.TB) []string {
I don't think that this function name is ok because when you need to create available users with T2 or Contacts referrals you will not able to understand what function you need to call.

2022-08-19 13:40 UTC, ice-laius commented on users/users_get_test.go
> +	GIVEN("database empty", func() {
done

2022-08-19 13:58 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +func TestService_GetUserByUsername_Failure_RegExp(t *testing.T) {
done

2022-08-19 13:58 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +		IT("is successfully returned", func() {
done

2022-08-19 13:59 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +	WHEN("get user by ID", func() {
done

2022-08-19 14:02 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +			assert.Equal(t, 400, status)
done

2022-08-19 14:11 UTC, ice-myles commented on users/users_get_test.go
> +			require.Equal(t, len(res), 0)
`assert.Equal` or I assume even `assert.Empty()` should be used here.

2022-08-19 14:14 UTC, ice-myles commented on users/users_get_test.go
> +	ctx = context.WithValue(ctx, "requestingUserIDCtxValueKey", "userid0") //nolint:staticcheck // No way
I meant where user from `ctx = context.WithValue(ctx, "requestingUserIDCtxValueKey", "userid0")` doesn't exist in the database. It will affect on the results. You've done already this thing for `GetUserName`, but `GetUsers` need to have the same case handling.

2022-08-19 14:45 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +	WHEN("get user by ID", func() {
by username.

2022-08-19 14:45 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +	WHEN("get user by ID", func() {
by username.

2022-08-19 18:37 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +	WHEN("get user by ID", func() {
done

2022-08-19 18:37 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +	WHEN("get user by ID", func() {
done

2022-08-19 18:38 UTC, ice-laius commented on users/users_get_test.go
> +			require.Equal(t, len(res), 0)
done

2022-08-19 18:38 UTC, ice-laius commented on users/users_get_test.go
> +			require.Equal(t, len(res), 0)
done

2022-08-20 07:55 UTC, ice-laius commented on cmd/fixture/fixture.go
> +func (b *TestConnectorsBridge) MustCreateAllAvailableUsers(ctx context.Context, tb testing.TB) []string {
done

2022-08-20 08:40 UTC, ice-laius commented on users/users_get_test.go
> +		} else {
fixed

2022-08-20 08:43 UTC, ice-laius commented on users/users_get_test.go
> +	ctx = context.WithValue(ctx, "requestingUserIDCtxValueKey", "userid0") //nolint:staticcheck // No way
ok added TestRepository_GetUsers_Success_NoRequestingUser

2022-08-21 20:13 UTC, ice-myles commented on users/users_get_test.go
> +		mustCreateSingleUser(ctx, t, 0)
You have GIVEN `create many users` and then you call mustCreate**Single**User function.
Nevertheless I repeat that we already have API to create users:
```
+var usr *User
+GIVEN("one user was created", func() {
+    usr = new(User).completelyRandomizeForCreate()
+    err = usr.mustCreate(ctx, t)
+})
-WHEN("get all users", func() {
+WHEN("get user by user id", func() {
-		res, err = usersRepository.GetUserByID(ctx, "userid0")
+		res, err = usersRepository.GetUserByID(ctx, usr.ID)
+})
THEN(func() {
    IT("...", func() {
        // here is bad idea to use some index, 
        // much better to pass usr and compare needed fields.
        // What is this step? It is not clear from the code.
-        verifyUserProfile(t, res, 0)
+        verifyUserProfile(t, res, usr)
    })
})
```

2022-08-21 20:20 UTC, ice-myles commented on users/users_get_test.go
> +func makeNewUser(idx int) *User {
This is also bad idea to use indexes. We have API to create random user:
```
usr:= new(User).completelyRandomizeForCreate()
require.NoError(t, usr.mustCreate(ctx, t))
```
It will create user with random generated username.

2022-08-21 20:22 UTC, ice-myles commented on users/users_get_test.go
> +	GIVEN("database empty", func() {
Make this pease on 1 line.

2022-08-21 20:24 UTC, ice-myles commented on users/users_get_test.go
> +		IT("is it error", func() {
Change please description to something decent.
It shouldn't ask if this is error, it should describe the result:
-IT("is it error", func() {
+IT("should have not found error")

2022-08-21 20:30 UTC, ice-myles commented on users/users_get_test.go
> +	for step := 0; step < 2; step++ {
By the way you definitely need to make
```
WHEN-THEN
WHEN-THEN
```
instead of using for and steps and
remove this`step` (these steps are terrible because if I can understand something in this test function, I need to find this function to understand the goal of this step at any other test functions).

2022-08-21 20:35 UTC, ice-myles commented on users/users_get_test.go
> +	for step := 0; step < 2; step++ {
```
-   WHEN("get all users", func() {
+   WHEN("trying to get user by username with established requestingUserIDCtxValueKey", func() {
-			if step == 1 {
				ctx = context.WithValue(ctx, "requestingUserIDCtxValueKey", actorUser.username) //nolint:staticcheck // No way
-			}
			res, err = usersRepository.GetUserByUsername(ctx, user.username)
		})
		THEN(func() { ....
+   WHEN("trying to get user by username with empty requestingUserIDCtxValueKey", func() {
+  			res, err = usersRepository.GetUserByUsername(ctx, user.username)
+		})
+		THEN(func() { ....
```

2022-08-21 20:42 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +		bridge.CreateUser(ctx, t, userID, token, reqBody)
Try to use `bridge.MustCreateDefaultUser()`. It is the ready to use function for this goal and you don't need to create `reqBody`.

2022-08-21 20:42 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +			assert.Equal(t, user.ReferredBy, userID)
You are checking here not all data. You need to check all outcome.

2022-08-21 20:47 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +func TestService_GetUserByID_Success(t *testing.T) {
Either wrong function name. or wrong function that you try to test.

2022-08-21 20:47 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +func TestService_GetUserByID_Failure_NoUser(t *testing.T) {
The same: either wrong function name, or function that you try to test.

2022-08-22 06:29 UTC, ice-laius commented on users/users_get_test.go
> +func makeNewUser(idx int) *User {
I use indexes to verify referrals

2022-08-22 06:39 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +func TestService_GetUserByID_Success(t *testing.T) {
I use existing 
rename it?

2022-08-22 06:40 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +			assert.Equal(t, user.ReferredBy, userID)
body here is long
I'd better make new func

2022-08-22 08:00 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +func TestService_GetUserByID_Failure_NoUser(t *testing.T) {
I use existing
rename it?

2022-08-22 08:01 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +		bridge.CreateUser(ctx, t, userID, token, reqBody)
done

2022-08-22 08:01 UTC, ice-laius commented on users/users_get_test.go
> +		IT("is it error", func() {
changed there a lot

2022-08-22 08:01 UTC, ice-laius commented on users/users_get_test.go
> +	GIVEN("database empty", func() {
done

2022-08-22 10:15 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +func TestService_GetUserByID_Success(t *testing.T) {
done

2022-08-22 10:15 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +			assert.Equal(t, user.ReferredBy, userID)
done

2022-08-22 10:16 UTC, ice-laius commented on users/users_get_test.go
> +	for step := 0; step < 2; step++ {
done

2022-08-22 10:17 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +		bridge.CreateUser(ctx, t, userID, token, reqBody)
done

2022-08-22 10:36 UTC, ice-myles commented on users/users_get_test.go
> +	GIVEN("database empty", func() {
Not done :))

2022-08-22 10:38 UTC, ice-myles commented on users/users_get_test.go
> +			require.Equal(t, "no user found with username username2: not found", err.Error())
We use asserts for comparing data, require is for error/no error.
```
require.Error()
require.NoError()
```
But
```
asssert.Equal
```

2022-08-22 10:48 UTC, ice-laius commented on users/users_get_test.go
> +			require.Equal(t, "no user found with username username2: not found", err.Error())
ok

2022-08-22 10:49 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +			assert.Equal(t, user.ReferredBy, userID)
Not good implemenration as you check only those fields that you want, not all fields, but okay, resolving this conversation not to interfere.

2022-08-22 10:55 UTC, ice-myles commented on cmd/fixture/fixture.go
> +func (b *TestConnectorsBridge) MustCreateAllAvailableUsers(ctx context.Context, tb testing.TB) []string {
Still not good naming. You have 3 types of referrals:
- t1
- t2
- contacts

You named `MustCreateRefferingUsers`. So what types of referrals will it cover? What referring does mean? We use everywhere `referrals` term.
And by the way:
```
-reffering
+referring
```

2022-08-22 11:30 UTC, ice-laius commented on cmd/fixture/fixture.go
> +func (b *TestConnectorsBridge) MustCreateAllAvailableUsers(ctx context.Context, tb testing.TB) []string {
we create mutually referring users :)
one user is referring to another

2022-08-22 18:04 UTC, ice-laius commented on users/users_get_test.go
> +		res, err = usersRepository.GetUsers(ctx, "user", 100, 0)
done

2022-08-23 07:46 UTC, ice-cronus requested changes

2022-08-23 07:46 UTC, ice-cronus commented on cmd/eskimo/users_test.go
> +package main
Cases for not authorized, different userID are not covered

2022-08-23 07:46 UTC, ice-cronus commented on cmd/eskimo/users_test.go
> +	tb.Fail()
any meaningful message here?

2022-08-23 07:46 UTC, ice-cronus commented on users/users_get_test.go
> +						if expectedLen > int(limit) {
how it can be more than limit? in case (not covered yet, btw) if offset > total users in db, it should return 0 records isn''t it?

2022-08-23 07:46 UTC, ice-cronus commented on users/users_get_test.go
> +		assert.GreaterOrEqual(tb, id, 0)
I think you can verify id with offset / initial data as well, to check if pagination works properly

2022-08-23 07:46 UTC, ice-cronus commented on users/users_get_test.go
> +			assert.Equal(t, fmt.Sprintf("failed to select user by id %v: not found", id), err.Error())
check error type ( require.ErrorIs(t, err, ErrNotFound) ) as well

2022-08-23 07:46 UTC, ice-cronus commented on users/users_get_test.go
> +			assert.Equal(t, fmt.Sprintf("no user found with username %v: not found", username), err.Error())
the same, check error with require.ErrorIs

2022-08-23 07:49 UTC, ice-myles requested changes

2022-08-23 07:49 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +		IT("user received well", func() {
```suggestion
		IT("received the user well", func() {
```
Because not _user received_, but _it received_ the user.

2022-08-23 07:49 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +func TestService_GetUserByID_Failure_NoUser(t *testing.T) {
```suggestion
func TestService_GetUserByID_Failure_UserNotFound(t *testing.T) {
```
better describes the test.

2022-08-23 07:49 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +func TestService_GetUserByUsername_Failure_NoUser(t *testing.T) {
```suggestion
func TestService_GetUserByUsername_Failure_UserNotFound(t *testing.T) {
```

2022-08-23 07:49 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +func TestService_GetUsers_Failure_RegExp(t *testing.T) {
```suggestion
func TestService_GetUsers_Success_WithEmptyDataResponse(t *testing.T) {
```

2022-08-23 07:49 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +		body, status = bridge.GetUserByUsername(ctx, t, "@#$user!!!", token)
I saw that eskimo-hut contains function `allInvalidUsernames`. Maybe it worth to use this function as well to test different cases for this function.

2022-08-23 07:49 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +
You should also add `OPERATION_NOT_ALLOWED` test cases for each of these 3 functions.
You can reach this if you will pass token that doesn't correspond to userID that executing the request.

2022-08-23 07:49 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +		assert.Equal(tb, val.Username, fmt.Sprintf("username%d", valIdx))
It's not enough to check only 2-3 fields, you should check all available outcome.

2022-08-23 07:49 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +	assert.Empty(tb, user.ReferralCount)
Are you sure that you checked all available outcome? :))

2022-08-23 07:49 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +		body, status = bridge.GetUsers(ctx, t, "u", token)
You need to check the result with different limits here as well. Don't forget to check default limit (if limit value is 0).

2022-08-23 07:49 UTC, ice-myles commented on users/users_get_test.go
> +	for _, keyword := range []string{"User", "First", "Last"} {
I would expand these 2 for loops into a lot of `WHEN-THEN`s as it will be more descriptive, but let's wait for any other comments, maybe I am wrong.

2022-08-23 07:49 UTC, ice-myles commented on users/users_get_test.go
> +func TestRepository_GetUsers_Success_EmptyDB(t *testing.T) { //nolint:paralleltest // We need a clean database.
```suggestion
func TestRepository_GetUsers_Success_EmptyDBWithRequestingUserID(t *testing.T) { //nolint:paralleltest // We need a clean database.
```

2022-08-23 07:49 UTC, ice-myles commented on users/users_get_test.go
> +func TestRepository_GetUsers_Success_NoRequestingUser(t *testing.T) { //nolint:paralleltest // We need a clean database.
```suggestion
func TestRepository_GetUsers_Success_EmptyDBWithoutRequestingUserID(t *testing.T) { //nolint:paralleltest // We need a clean database.
```

2022-08-23 07:49 UTC, ice-myles commented on users/users_get_test.go
> +	GIVEN("create single", func() {
```suggestion
	GIVEN("create single user", func() {
```

2022-08-23 07:49 UTC, ice-myles commented on users/users_get_test.go
> +func TestRepository_GetUserByUsername_Failure_NoUserName(t *testing.T) { //nolint:paralleltest // We need a clean database.
```suggestion
func TestRepository_GetUserByUsername_Failure_UserNameNotFound(t *testing.T) { //nolint:paralleltest // We need a clean database.
```

2022-08-23 07:49 UTC, ice-myles commented on users/users_get_test.go
> +func TestRepository_GetUserByID_Failure_NoUserID(t *testing.T) { //nolint:paralleltest // We need a clean database.
```suggestion
func TestRepository_GetUserByID_Failure_UserIDNotFound(t *testing.T) { //nolint:paralleltest // We need a clean database.
```

2022-08-23 07:49 UTC, ice-myles commented on users/users_get_test.go
> +	WHEN("get username2", func() {
```suggestion
	WHEN("get user by username when no such user in the database", func() {
```

2022-08-23 08:06 UTC, ice-cronus commented on users/users_get_test.go
> +	for _, keyword := range []string{"User", "First", "Last"} {
not if it'll better without loops. We have a lot of cases to test here ( different keywords, limits, offset).
I suggest something like table testing like, may be that will look better
`
	cases:=[]TestCase{
		{Limit: 0, Offset:0, Keyword:"Last"},
		{Limit: 0, Offset:0, Keyword:"First"},
		....
	}
`

2022-08-23 08:57 UTC, ice-laius commented on users/users_get_test.go
> +						if expectedLen > int(limit) {
limit is variable here

2022-08-23 09:01 UTC, ice-laius commented on users/users_get_test.go
> +			assert.Equal(t, fmt.Sprintf("failed to select user by id %v: not found", id), err.Error())
done assert

2022-08-23 09:01 UTC, ice-laius commented on users/users_get_test.go
> +			assert.Equal(t, fmt.Sprintf("no user found with username %v: not found", username), err.Error())
done assert

2022-08-23 09:18 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +		IT("user received well", func() {
the passive voice
user has been received well -> user received well
target destroyed
access granted
data acquired

2022-08-23 09:20 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +func TestService_GetUserByID_Failure_NoUser(t *testing.T) {
done

2022-08-23 09:20 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +func TestService_GetUserByUsername_Failure_NoUser(t *testing.T) {
done

2022-08-23 09:20 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +func TestService_GetUsers_Failure_RegExp(t *testing.T) {
done

2022-08-23 09:37 UTC, ice-laius commented on users/users_get_test.go
> +func TestRepository_GetUsers_Success_NoRequestingUser(t *testing.T) { //nolint:paralleltest // We need a clean database.
done

2022-08-23 09:38 UTC, ice-laius commented on users/users_get_test.go
> +	GIVEN("create single", func() {
done

2022-08-23 09:39 UTC, ice-laius commented on users/users_get_test.go
> +func TestRepository_GetUserByUsername_Failure_NoUserName(t *testing.T) { //nolint:paralleltest // We need a clean database.
done

2022-08-23 09:39 UTC, ice-laius commented on users/users_get_test.go
> +func TestRepository_GetUserByID_Failure_NoUserID(t *testing.T) { //nolint:paralleltest // We need a clean database.
done

2022-08-23 09:39 UTC, ice-laius commented on users/users_get_test.go
> +	WHEN("get username2", func() {
done

2022-08-23 09:55 UTC, ice-laius commented on users/users_get_test.go
> +						if expectedLen > int(limit) {
added offset 100

2022-08-23 12:05 UTC, ice-myles requested changes

2022-08-23 12:05 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +			assert.Equal(t, body, "[]")
```suggestion
			assert.Equal(t, "[]", body)
```
**expected** value is the **second** argument, **actual** is the **third**, so is better to change it, otherwise when you get error in the tests it can be difficult to understand what happened.

2022-08-23 12:05 UTC, ice-myles commented on users/users_get_test.go
> +						assert.LessOrEqual(t, len(res), int(limit))
```suggestion
						assert.LessOrEqual(t, int(limit), len(res))
```
**expected** value is the **second** argument, **actual** is the **third**. In this case `res` is actual.

2022-08-23 12:05 UTC, ice-myles commented on cmd/eskimo/users_test.go
> +		assert.Equal(tb, val.ID, allUsers[valIdx])
**expected** value is the second argument, **actual** is the third. And below the same. `val` here is actual because it is taken from body.

2022-08-23 15:36 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +		body, status = bridge.GetUserByUsername(ctx, t, "@#$user!!!", token)
done

2022-08-23 15:37 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +			assert.Equal(t, body, "[]")
done

2022-08-23 15:38 UTC, ice-laius commented on users/users_get_test.go
> +						assert.LessOrEqual(t, len(res), int(limit))
done

2022-08-23 15:39 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +		assert.Equal(tb, val.ID, allUsers[valIdx])
done

2022-08-23 15:42 UTC, ice-laius commented on users/users_get_test.go
> +	for _, keyword := range []string{"User", "First", "Last"} {
I think current version is simple and visually fine :/

2022-08-24 06:01 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +package main
I didnt get this

2022-08-24 06:03 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +	tb.Fail()
tb.Fatal("unable to find value index")

2022-08-24 15:47 UTC, ice-laius commented on users/users_get_test.go
> +		assert.GreaterOrEqual(tb, id, 0)
done in separate func

2022-08-24 15:48 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +		assert.Equal(tb, val.Username, fmt.Sprintf("username%d", valIdx))
done

2022-08-24 15:48 UTC, ice-laius commented on cmd/eskimo/users_test.go
> +	assert.Empty(tb, user.ReferralCount)
done

2022-08-26 15:23 UTC, ice-laius commented on users/users_get_test.go
> +func TestRepository_GetUsers_Success_EmptyDB(t *testing.T) { //nolint:paralleltest // We need a clean database.
TestRepository_GetUsers_Success_EmptyDBWithRequestingUserID

2023-01-13 17:36 UTC, ice-myles commented
Was rebased into the `feature/fixing-tests` branch. Will continue from that branch.

2023-01-13 17:36 UTC, closed without merging