SQL for device metadata replacement
ice-blockchain/eskimo pull request #35
Opened 2022-08-24 15:39 UTC by ice-cronus

ReplaceDeviceMetadata is used NoSQL for replace metadata in database, so DB checks (like if user exists) was never called.
This PR fixes that issue, ReplaceDeviceMetadata was rewritten using SQL to preserve DB references.

2022-08-24 17:11 UTC, ice-ares requested changes

2022-08-24 17:11 UTC, ice-ares commented on users/internal/device/metadata/metadata.go
> +   			:readable_version,:fingerprint,:instance_id,:hardware,:product,:device,:type,:tags,:device_id,:device_type,:device_name,:brand,:carrier,:manufacturer,
indent properly

2022-08-24 17:11 UTC, ice-ares commented on users/internal/device/metadata/metadata.go
> +	sql, params := r.prepareSQL(metadata)
inline it

2022-08-24 17:11 UTC, ice-ares commented on users/internal/device/metadata/contract.go
>  	Model struct {
can this be private?

2022-08-24 17:11 UTC, ice-ares commented on users/internal/device/metadata/metadata.go
>  	metadata.UpdatedAt = time.Now()
move this inside DeviceMetadata, and make sure the field order is correct in DB

2022-08-25 11:12 UTC, ice-cronus commented on users/internal/device/metadata/contract.go
>  	Model struct {
It seems no, it is used in fixture package in search for existing DB values ( AllExistingDeviceMetadata )

2022-08-25 13:06 UTC, ice-ares commented on users/internal/device/metadata/contract.go
>  	Model struct {
then move it in the public section

2022-08-25 13:07 UTC, ice-ares commented on users/internal/device/metadata/metadata.go
> +	metadata.UpdatedAt = time.Now()
unnecessary change

2022-08-25 13:08 UTC, ice-ares commented on users/internal/device/metadata/metadata.go
> +	metadata.UpdatedAt = time.Now()
actually, you need to set updatedAt in the input

2022-08-25 13:08 UTC, ice-ares commented on users/internal/device/metadata/metadata.go
> +func (dm *Model) prepareSQL() (string, map[string]interface{}) {
replaceSQL

2022-08-25 14:15 UTC, ice-ares approved these changes

2022-08-25 14:16 UTC, merged