GetTopCounties testing
ice-blockchain/eskimo pull request #39
Opened 2022-09-21 07:34 UTC by ice-laius

2022-09-21 22:04 UTC, ice-myles requested changes

2022-09-21 22:04 UTC, ice-myles commented on users/top_countries_test.go
> +	var res []*CountryStatistics
Move `res` and `err` variables closer to the place where it is used. The same for `userCount` and `country`.

2022-09-21 22:04 UTC, ice-myles commented on users/top_countries_test.go
> +	var res []*CountryStatistics
The same here: we define variables in the tests closer to the places where they used.
This recommendation for all tests.

2022-09-22 06:36 UTC, ice-laius commented on users/top_countries_test.go
> +	windowedCtx, windowedCancel := context.WithTimeout(ctx, time.Duration(expected)*time.Second)
why fixed length is better then number-dependent?
I have 66 users in sorting test

2022-09-22 06:38 UTC, ice-laius commented on cmd/eskimo/top_countries_test.go
> +	countryList := map[string]struct{}{"AL": {}, "RU": {}, "RO": {}, "US": {}, "AT": {}, "HU": {}, "GB": {}, "UA": {}, "FR": {}, "NO": {}}
cuz I use the same type for creating and searching
todo move map to single place

2022-09-22 07:04 UTC, ice-laius commented on users/top_countries_test.go
> +	res := new([]*CountryStatistics)
done

2022-09-22 07:06 UTC, ice-laius commented on users/top_countries_test.go
> +func assertUsersCount(ctx context.Context, tb testing.TB, expected uint64) {
assertUsersPerCountry asserts for users with specified country
so should be something like assertUsersPerAllCountries

2022-09-22 07:07 UTC, ice-laius commented on users/top_countries_test.go
> +		WHEN("get top countries", func() {
done

2022-09-22 07:09 UTC, ice-laius commented on cmd/eskimo/top_countries_test.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
done

2022-09-22 07:12 UTC, ice-laius commented on cmd/eskimo/top_countries_test.go
> +	var body fixture.ActualRespBody
done

2022-09-22 07:13 UTC, ice-laius commented on cmd/eskimo/top_countries_test.go
> +			countryStats := verifyGetTopCountriesBody(t, body)
it should be discussed
I dont like comparing data as strings

2022-09-22 07:14 UTC, ice-laius commented on cmd/eskimo/top_countries_test.go
> +	userIDs, token := bridge.GetAllTestingAuthorizations()
done

2022-09-22 07:14 UTC, ice-laius commented on cmd/eskimo/top_countries_test.go
> +	countryStats := new([]*users.CountryStatistics)
done

2022-09-22 07:16 UTC, ice-laius commented on users/top_countries_test.go
> +func verifyUsersCountry(tb testing.TB, users []*CountryStatistics, country devicemetadata.Country) {
assertUsersPerCountry uses database

2022-09-22 07:17 UTC, ice-laius commented on users/top_countries_test.go
> +	var res []*CountryStatistics
done

2022-09-22 07:17 UTC, ice-laius commented on users/top_countries_test.go
> +	var res []*CountryStatistics
done

2023-01-13 17:34 UTC, ice-myles commented
Was rebased into the `feature/fixing-tests` branch.

2023-01-13 17:34 UTC, closed without merging