Top countries stats
ice-blockchain/eskimo pull request #4
Opened 2022-05-04 15:50 UTC by kfedor

2022-05-05 12:34 UTC, victor-oancea-leftclick-io requested changes

2022-05-05 12:34 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/eskimo_hut.go
> +	_ = s.ipDatabase.Close()
log it

2022-05-05 12:34 UTC, victor-oancea-leftclick-io commented on ip2country/contract.go
> +package ip2country
ip2location

2022-05-05 12:34 UTC, victor-oancea-leftclick-io commented on ip2country/contract.go
> +type IPDatabase struct {
make it private and rename it to ip2locationRepository

2022-05-05 12:34 UTC, victor-oancea-leftclick-io commented on ip2country/ip2country.go
> +	db, err := ip2location.OpenDB("./ipdb.bin")
check if ctx error != nil and return it

2022-05-05 12:34 UTC, victor-oancea-leftclick-io commented on ip2country/ip2country.go
> +	db, err := ip2location.OpenDB("./ipdb.bin")
OpenDB(cfg.IP2Location.BinaryLocation)

2022-05-05 12:34 UTC, victor-oancea-leftclick-io commented on ip2country/ip2country.go
> +func New(_ context.Context) *IPDatabase {
return Repository

2022-05-05 12:34 UTC, victor-oancea-leftclick-io commented on ip2country/ip2country.go
> +	results, err := i.db.Get_all(ip)
check if ctx error != nil and return it

2022-05-05 12:34 UTC, victor-oancea-leftclick-io commented on ip2country/contract.go
> +	GetCountry(context.Context, string) string
create a typeAlias IP = string and use it

2022-05-05 12:34 UTC, victor-oancea-leftclick-io commented on users/contract.go
> +		GetTopCountries(context.Context, uint64, uint64) ([]*CountryStatistics, error)
typealias those 2 uint64's

2022-05-05 12:34 UTC, victor-oancea-leftclick-io commented on users/users.go
> +	startUsersMessageConsuming(ctx, db)
use the same pattern to start this as on ricky

2022-05-05 12:34 UTC, victor-oancea-leftclick-io commented on users/users.go
> +type usersMessageConsumer struct {
rename to usersSource and move it to contract

2022-05-05 12:34 UTC, victor-oancea-leftclick-io commented on users/users.go
> +	return messagebroker.MustConnectAndStartConsuming(ctx, func() {}, applicationYamlKey, processors)
use the same pattern as in ricky

2022-05-05 16:52 UTC, victor-oancea-leftclick-io requested changes

2022-05-05 16:52 UTC, victor-oancea-leftclick-io commented on users/users.go
> +	finishers := make([]func(), 0, 1+1)
we don't have a need for this. In ricky there were 3rd party processes for some consumers that needed to be properly closed and cleaned up, we don't have any

2022-05-05 16:52 UTC, victor-oancea-leftclick-io commented on users/users.go
> +func (mb *usersSource) Process(ctx context.Context, m *messagebroker.Message) error {
i think you might need to move this to a separate go file named users_source cuz you'd have alot of logic to do for it

2022-05-05 16:52 UTC, victor-oancea-leftclick-io commented on ip2location/ip2country.go
> +		return &ip2locationRepository{}
we panic

2022-05-05 16:52 UTC, victor-oancea-leftclick-io commented on ip2location/ip2country.go
> +	if i.db == nil {
won't be needed

2022-05-05 16:52 UTC, victor-oancea-leftclick-io commented on ip2location/ip2country.go
> +		log.Panic(errors.Wrap(ctx.Err(), "context error"))
just return empty

2022-05-05 16:52 UTC, victor-oancea-leftclick-io commented on ip2location/contract.go
> +var cfg config
const, then global vars, then type definition, thats the order

2022-05-05 18:52 UTC, kfedor commented on users/users.go
> +func (mb *usersSource) Process(ctx context.Context, m *messagebroker.Message) error {
done

2022-05-05 18:54 UTC, kfedor commented on ip2location/contract.go
> +var cfg config
done

2022-05-05 18:55 UTC, kfedor commented on ip2location/ip2country.go
> +		return &ip2locationRepository{}
ok

2022-05-05 18:55 UTC, kfedor commented on ip2location/ip2country.go
> +	if i.db == nil {
with panic yes

2022-05-06 09:58 UTC, victor-oancea-leftclick-io requested changes

2022-05-06 09:58 UTC, victor-oancea-leftclick-io commented on cmd/eskimo-hut/countrycodes.map
> +AF
I think we need to do a refactor:

move this new country validation logic into ip2location package, in a new method "Validate(Country) error"

rename GetCountry(IP) to Get(IP)

rename the package ip2location to "countries"

2022-05-11 22:03 UTC, victor-oancea-leftclick-io commented on users/top_countries.go
> +	err := mb.db.UpsertAsync("USERS_PER_COUNTRY", []interface{}{country, 1}, arOp).GetTyped(&res)
u can use that db struct instead of that []interface{}

2022-05-12 00:12 UTC, azayats-leftclick commented on users/users_add.go
> +	return errors.Wrap(u.sendUsersMessage(ctx, UserSnapshot{User: user, Before: nil}), "failed to send user created message")
Hm... This broke my freezer processor for the user events, cause it relies on the User struct itself.... 
https://github.com/ice-blockchain/freezer/blob/a33725f63afab78cdab3429a1791f45207e89975/economy/internal/storages/user_economy/contract.go#L59

2022-05-12 06:03 UTC, kfedor commented on users/users_add.go
> +	return errors.Wrap(u.sendUsersMessage(ctx, UserSnapshot{User: user, Before: nil}), "failed to send user created message")
how can this be ?

2022-05-12 06:08 UTC, kfedor commented on users/top_countries.go
> +	err := mb.db.UpsertAsync("USERS_PER_COUNTRY", []interface{}{country, 1}, arOp).GetTyped(&res)
how to use it?
I always get Invalid MsgPack - packet body (0x14)

2022-05-12 06:55 UTC, azayats-leftclick commented on users/users_add.go
> +	return errors.Wrap(u.sendUsersMessage(ctx, UserSnapshot{User: user, Before: nil}), "failed to send user created message")
You've changed the struct to send to user-events topic, that's it.
The freezer-refregerant's processor for this topic used uses this events to fill in `user_economy`, `total_users`, `t1_referral_earnings` and `t2_referral_earnings` spaces.
So, I need to change it.

2022-05-12 09:23 UTC, nusanovkornilov-leftclick commented on users/users_delete.go
> +	return errors.Wrap(u.sendUsersMessage(ctx, UserSnapshot{User: gUser.deleted(), Before: nil}), "failed to send deleted user message")
Shouldn't they be reversed? Deleted user is before, new user is nil ( because of deleted)?

2022-05-12 09:37 UTC, azayats-leftclick commented on users/users_delete.go
> +	return errors.Wrap(u.sendUsersMessage(ctx, UserSnapshot{User: gUser.deleted(), Before: nil}), "failed to send deleted user message")
Yeah, i suppose yes, if we get in mind trigger behavior with the NEW and OLD record set.

2022-05-12 09:44 UTC, kfedor commented on users/users_delete.go
> +	return errors.Wrap(u.sendUsersMessage(ctx, UserSnapshot{User: gUser.deleted(), Before: nil}), "failed to send deleted user message")
it's controversial
we have user_old = gUser and modified user_new = gUser.deleted() which we rely on

2022-05-12 10:26 UTC, azayats-leftclick submitted a review, later dismissed

2022-05-12 12:14 UTC, victor-oancea-leftclick-io commented on application.yaml
> +  binaryLocation: ./ip_db/IP2LOCATION-LITE-DB1.BIN
ip2LocationBinaryPath

2022-05-12 12:17 UTC, victor-oancea-leftclick-io commented on cmd/eskimo/referrals.go
> +	/*
@kfedor  @nusanovkornilov-leftclick 's solution here is better

2022-05-12 12:17 UTC, victor-oancea-leftclick-io commented on cmd/eskimo/referrals.go
> +	/*
same thing here

2022-05-12 12:22 UTC, victor-oancea-leftclick-io commented on application.yaml
> +  binaryLocation: ./ip_db/IP2LOCATION-LITE-DB1.BIN
also, put the binary in root, so ./IP2LOCATION-LITE-DB1.BIN

2022-05-12 12:25 UTC, kfedor commented on countries/countries.go
> +	}
do you mean len(v) ?

2022-05-12 12:30 UTC, kfedor commented on application.yaml
> +  binaryLocation: ./ip_db/IP2LOCATION-LITE-DB1.BIN
done

2022-05-12 12:35 UTC, kfedor commented on cmd/eskimo/referrals.go
> +	/*
merging with incomplete branch?

2022-05-12 13:08 UTC, kfedor commented on users/contract.go
> -		//nolint:unused // Because it is used by the msgpack library for marshalling/unmarshalling.
lost during merge

2022-05-12 13:13 UTC, victor-oancea-leftclick-io commented on cmd/eskimo/referrals.go
> +	/*
nope,  how he "fixed" those linters

2022-05-12 13:14 UTC, victor-oancea-leftclick-io commented on countries/countries.go
> +	}
same thing

2022-05-12 13:41 UTC, victor-oancea-leftclick-io commented on users/users_delete.go
> +	return errors.Wrap(u.sendUsersMessage(ctx, UserSnapshot{User: gUser.deleted(), Before: nil}), "failed to send deleted user message")
🤔  I think we need to remove that DeletedAt from User and reverse them for delete, the embedded *User is nil and before is gUser

2022-05-12 13:48 UTC, azayats-leftclick commented on users/users_delete.go
> +	return errors.Wrap(u.sendUsersMessage(ctx, UserSnapshot{User: gUser.deleted(), Before: nil}), "failed to send deleted user message")
If it will be implemented, I've also need to change source processor to proper handle deletion.
For now, it relies on filled DeletedAt field.

2022-05-12 13:53 UTC, victor-oancea-leftclick-io commented on users/users_delete.go
> +	return errors.Wrap(u.sendUsersMessage(ctx, UserSnapshot{User: gUser.deleted(), Before: nil}), "failed to send deleted user message")
@azayats-leftclick you worry too much. 

We'll change alot of stuff in the development process, so be prepared to change the same thing multiple times. 
Thats to be expected.


We write code to fix problems, to implement the business, not to avoid being uncomfortable with changing it 10 times until we get it right.

2022-05-13 08:25 UTC, victor-oancea-leftclick-io commented on users/users_delete.go
> +	return errors.Wrap(u.sendUsersMessage(ctx, UserSnapshot{User: gUser.deleted(), Before: nil}), "failed to send deleted user message")
@kfedor are you fixing this?

2022-05-13 08:28 UTC, victor-oancea-leftclick-io requested changes

2022-05-13 08:28 UTC, victor-oancea-leftclick-io commented on users/users_modify.go
> +	return errors.Wrap(u.sendUsersMessage(ctx, UserSnapshot{User: user, Before: gUser}), "failed to send updated user message")
User should be gUser with the fields from user overriden

2022-05-13 11:27 UTC, kfedor commented on users/users_modify.go
> +	return errors.Wrap(u.sendUsersMessage(ctx, UserSnapshot{User: user, Before: gUser}), "failed to send updated user message")
i merged

2022-05-13 11:32 UTC, victor-oancea-leftclick-io commented on users/users_modify.go
> +	return errors.Wrap(u.sendUsersMessage(ctx, UserSnapshot{User: user, Before: gUser}), "failed to send updated user message")
don't see where

2022-05-13 11:33 UTC, kfedor commented on users/users_modify.go
> +	return errors.Wrap(u.sendUsersMessage(ctx, UserSnapshot{User: user, Before: gUser}), "failed to send updated user message")
return errors.Wrap(u.sendUsersMessage(ctx, UserSnapshot{User: gUser.merge(user), Before: gUser}), "failed to send updated user message")

2022-05-13 12:28 UTC, victor-oancea-leftclick-io approved these changes

2022-05-13 14:22 UTC, victor-oancea-leftclick-io approved these changes

2022-05-13 14:32 UTC, nusanovkornilov-leftclick approved these changes

2022-05-13 14:37 UTC, merged