auth email rate limiting
ice-blockchain/eskimo pull request #43
Opened 2023-07-17 09:33 UTC by ice-cronus

Store count of login attempts into dedicated table with IP PK.
If user reaches limit for IP address for pending confirmations - we're not allow to send requests from that address anymore until previous pending confirmations will be succeeded.

2023-07-17 10:40 UTC, ice-ares requested changes

2023-07-17 10:40 UTC, ice-ares commented on auth/email_link/DDL.sql
> +           login_attempts                         BIGINT DEFAULT 0 NOT NULL,
Do u need these 3 here? They are independent of everything

2023-07-17 10:40 UTC, ice-ares commented on auth/email_link/DDL.sql
> +       login_attempts BIGINT DEFAULT 0 NOT NULL,
Db check. <= 10

2023-07-17 10:40 UTC, ice-ares commented on auth/email_link/DDL.sql
> +       login_attempts BIGINT DEFAULT 0 NOT NULL,
Flow is.

insert into this new table 

On update set attempts +=1

. Then in code when db check fails, u return error.


If ok, proceed with existing logic

2023-07-17 10:40 UTC, ice-ares commented on auth/email_link/DDL.sql
> +       blocked_until         TIMESTAMP,
U dont need this

2023-07-20 10:32 UTC, ice-cronus commented on auth/email_link/DDL.sql
> +       login_attempts BIGINT DEFAULT 0 NOT NULL,
Do we really need check on DB? Is RETURNING attempts and handling in the code an option here? Cuz if we keep check in the code it would be more configurable with application.yaml

2023-07-20 10:47 UTC, ice-ares commented on auth/email_link/DDL.sql
> +       login_attempts BIGINT DEFAULT 0 NOT NULL,
yes. its a lot more configurable with a db check

2023-07-20 14:39 UTC, ice-cronus commented on auth/email_link/DDL.sql
> +       login_attempts BIGINT DEFAULT 0 NOT NULL,
Added it. But may be it would be better to place it in cfg and do something like
```
ALTER TABLE sign_ins_per_ip
      DROP CONSTRAINT con,
      ADD CONSTRAINT con  CHECK (login_attempts <= %v)
```
And process it with spriftf, not to update it manually in DB it we would need more quota in the future

2023-07-20 15:27 UTC, ice-ares commented on auth/email_link/DDL.sql
> +       login_attempts BIGINT DEFAULT 0 NOT NULL,
Add if not exists, dont replace it every time service restarts

2023-07-21 11:47 UTC, merged