Script to update email for users with phone number only
ice-blockchain/eskimo pull request #45
Opened 2023-07-17 14:21 UTC by ice-myles

Script to update email for users, that were registered before by phone number, to have possibility to use ice auth.

2023-07-17 14:28 UTC, ice-ares commented on cmd/scripts/update_email.go
> +func getUsersForUpdate(ctx context.Context, db *storage.DB) (records []*record, err error) {
Dont return any errors in scrips, always panic. And make sure the run can be retried (is idempotent)

2023-07-17 14:29 UTC, ice-ares commented on cmd/scripts/update_email.go
> +func getUsersForUpdate(ctx context.Context, db *storage.DB) (records []*record, err error) {
Context is also always background in scripts

2023-07-17 14:29 UTC, ice-ares commented on cmd/scripts/update_email.go
> +	result, err := storage.Get[users.User](ctx, db, `SELECT * FROM users WHERE phone_number = $1`, phoneNumber)
One sql, with join for input

2023-07-17 14:31 UTC, ice-ares commented on cmd/scripts/update_email.go
> +	result, err := storage.Get[users.User](ctx, db, `SELECT * FROM users WHERE phone_number = $1`, phoneNumber)
Think of pagination

2023-07-17 14:32 UTC, ice-ares commented on cmd/scripts/update_email.go
> +	usersProcessor := users.StartProcessor(ctx, cancel)
Nope, u need to disable the consumer. Create a .patch that u apply to do that

2023-07-17 14:32 UTC, ice-ares commented on cmd/scripts/update_email.go
> +	ctx, cancel := context.WithCancel(context.Background())
Not needed

2023-07-17 14:33 UTC, ice-ares commented on cmd/scripts/update_email.go
> +	log.Panic(err, "can't get users for update")
No, wrap the error, thats not how that logging api works

2023-07-17 14:34 UTC, ice-ares commented on cmd/scripts/update_email.go
> +		if err := usersProcessor.ModifyUser(ctx, &updUsr, nil); err != nil {
Dont u need some sort of value in context?

2023-07-17 14:35 UTC, ice-ares commented on cmd/scripts/update_email.go
> +		if err := authClient.UpdateEmail(ctx, usr.ID, value.Email); err != nil {
How do we know this uses firebase?

2023-07-17 14:35 UTC, ice-ares commented on cmd/scripts/update_email.go
> +		if _, err := authEmailLinkClient.UpdateMetadata(ctx, usr.ID, &md); err != nil {
Dont we have to modify the email there as well?

2023-07-17 14:36 UTC, ice-ares commented on cmd/scripts/update_email.go
> +			log.Error(err, "can't update metadata for userID:%v, phoneNumber:%v", usr.ID, value.PhoneNumber)
Log panic everything

2023-07-17 14:37 UTC, ice-ares commented on cmd/scripts/.testdata/application.yaml
> +# SPDX-License-Identifier: ice License 1.0
Remove it, u dont need it

2023-07-17 16:05 UTC, ice-myles commented on cmd/scripts/update_email.go
> +		if err := usersProcessor.ModifyUser(ctx, &updUsr, nil); err != nil {
Here can be only lastUpdatedAt used, but it doesn't look that it can be used here as we don't have the state with infinite context.

2023-07-17 16:07 UTC, ice-myles commented on cmd/scripts/update_email.go
> +		if err := authClient.UpdateEmail(ctx, usr.ID, value.Email); err != nil {
The problem that we do this script for users who don't have any data in metadata table (they simply logged in by phone number some time ago, and then they can't log in by ice auth due to they don't have email). So we can't detect for them who they are: ice or firebase. If they didn't set this value someway before. But if they set, it means they are not required in this script.

2023-07-17 16:08 UTC, ice-myles commented on cmd/scripts/update_email.go
> +		if _, err := authEmailLinkClient.UpdateMetadata(ctx, usr.ID, &md); err != nil {
Only lastUpdatedAt here can be, but we don't have any receiver of this checksum from Modify request.

2023-07-17 16:29 UTC, ice-ares commented on cmd/scripts/update_email.go
> +		if err := authClient.UpdateEmail(ctx, usr.ID, value.Email); err != nil {
No. The whole purpose of that call is to update the email in firebase. So the question remains: How do we know authClient.UpdateEmail updates the email in firebase?

2023-07-17 20:02 UTC, ice-myles commented on cmd/scripts/.testdata/application.yaml
> +# SPDX-License-Identifier: ice License 1.0
Actually needed as users processor is started and require to have the configuration data, auth client requires as well. 

UPD: Hm, though most likely it depends on from what folder to run script.

2023-07-17 20:06 UTC, ice-myles commented on cmd/scripts/update_email.go
> +		if err := authClient.UpdateEmail(ctx, usr.ID, value.Email); err != nil {
So authfixture.GetUser only, as we don't have GetUser at the prod auth contract. Nevertheless is a good idea to add if data was updated in proper way.

2023-07-17 20:08 UTC, ice-myles commented on cmd/scripts/update_email.go
> +	result, err := storage.Get[users.User](ctx, db, `SELECT * FROM users WHERE phone_number = $1`, phoneNumber)
If I am right understand that you are talking about updating by batches (take 1000, handle, offset += 1000, handle, etc)? Don't see the big sense to add limit/offset as cmd parameters.

2023-07-17 20:25 UTC, ice-myles commented on cmd/scripts/update_email.go
> +func getUsersForUpdate(ctx context.Context, db *storage.DB) (records []*record, err error) {
Question: if every error should be handled by panic, and SQL API already has the retry functionality, so what are the places to add retries?

2023-07-18 20:31 UTC, ice-ares requested changes

2023-07-18 20:31 UTC, ice-ares commented on cmd/scripts/update_email/update_email.go
> +	for context.Background().Err() == nil {
Useless cond

2023-07-18 20:31 UTC, ice-ares commented on cmd/scripts/update_email/update_email.go
> +	totalCount := getUsersForUpdateCount(db)
Why?  It's irrelevant

2023-07-18 20:31 UTC, ice-ares commented on cmd/scripts/update_email/update_email.go
> +			if record.HandledAt != nil || record.UserEmail == record.ToUpdateEmail {
No. Do it via sql

2023-07-18 20:31 UTC, ice-ares commented on cmd/scripts/update_email/update_email.go
> +				markAsHandled(db, usr.ToUpdateEmail, index)
Do u need that? A join would do the same thing

2023-07-18 20:31 UTC, ice-ares commented on cmd/scripts/update_email/update_email.go
> +				JOIN update_email_temporary upd
Select from this first, and right join with users on email and phone number

2023-07-18 20:31 UTC, ice-ares commented on cmd/scripts/update_email/update_email.go
> +				u.email   AS user_email,
That's irrelevant. At best u can check for it to be = id

2023-07-18 20:31 UTC, ice-ares commented on cmd/scripts/update_email/update_email.go
> +				u.phone_number,
Irrelevant. PhoneNumber is just the way u identify the user

2023-07-18 20:31 UTC, ice-ares commented on cmd/scripts/update_email/update_email.go
> +			ORDER BY u.created_at ASC
Order by phone number in the nEw table

2023-07-18 20:31 UTC, ice-ares commented on cmd/scripts/update_email/update_email.go
> +	if result == nil {
Not needed

2023-07-18 20:31 UTC, ice-ares commented on cmd/scripts/update_email/update_email.go
> +func getUsersForUpdateCount(db *storage.DB) uint64 {
Not needed

2023-07-18 23:55 UTC, ice-ares commented on cmd/scripts/merge_firebase_phone_login_with_ice_email_login/merge_firebase_phone_login_with_ice_email_login.go
> +					ON u.email != m.email
==

2023-07-19 14:30 UTC, merged