Precalculations of referral counts
ice-blockchain/eskimo pull request #5
Opened 2023-04-21 16:38 UTC by ice-cronus

This PR adds a dedicated table for storing referral counts for the user to avoid long count(*) calls on psql.

2023-04-22 10:33 UTC, ice-ares commented on go.mod
> +	github.com/quic-go/quic-go => github.com/quic-go/quic-go v0.33.0
Why?

2023-04-22 10:35 UTC, ice-ares commented on users/DDL.sql
> +);
Move userid and date at the end, in this order:

date
Userid

2023-04-22 10:37 UTC, ice-ares commented on users/users_get.go
> +			COALESCE(refs.t1_today, 0) 					  as t1_referral_count,
This is only what registered today,  not the total number of referrals user has

2023-04-22 10:38 UTC, ice-ares commented on users/users_get.go
> +			COALESCE(refs.t1_today, 0) 					  as t1_referral_count,
Add 2 new fields then for that: t1 and t2

2023-04-22 10:39 UTC, ice-ares commented on users/users_get.go
> +					COALESCE(refs.t1_today) AS t1_referral_count,
Coalesce needs a 2nd param

2023-04-22 10:45 UTC, ice-ares commented on users/users_referrals.go
> +	elapsedDaysSinceLastRefCountsUpdate := int(nowMidnight.Sub(*res.Date.Time).Nanoseconds() / int64(hoursInOneDay*stdlibtime.Hour))
Why do u need this? Result has to have 5 days all the time

2023-04-22 10:48 UTC, ice-ares commented on users/users_referrals.go
> +	result := make([]*ReferralAcquisition, maxDaysReferralsHistory) //nolint:makezero // We're know size for sure.
Make sure all the elements in here have different days

2023-04-22 10:51 UTC, ice-ares commented on users/users_referrals.go
> +	if us.ReferredBy == us.ID || us.Before == nil || us.User == nil || us.Before.ReferredBy == us.ReferredBy {
|| us.ReferredBy == “”

2023-04-22 11:01 UTC, ice-ares commented on users/users_referrals.go
> +			   WHERE ((user_id = $2 AND date = $1) OR user_id = t2.id)
Replace $2 with t2.id

2023-04-22 11:02 UTC, ice-ares commented on users/users_referrals.go
> +			WITH t2 AS (
Thats t0

2023-04-22 11:02 UTC, ice-ares commented on users/users_referrals.go
> +		WITH t2 AS (
T0

2023-04-22 11:06 UTC, ice-ares commented on users/users_referrals.go
> +		return r.incrementReferralCount(ctx, userID)
U need a condition to stop the recursion

2023-04-22 11:06 UTC, ice-ares commented on users/users_referrals.go
> +		WITH t2 AS (
T0

2023-04-22 11:10 UTC, ice-ares commented on users/users_referrals.go
> +			   COALESCE((SELECT t2_today from referral_acquisition_history where user_id = t2.id),0) AS t2,
Whats the number of t2 referrals ur t0 has acquired today have to do with you?

2023-04-22 11:11 UTC, ice-ares commented on users/users_referrals.go
> +            UNION SELECT NULL as id) tmp LIMIT 1
Why do u need to union there?

2023-04-22 11:11 UTC, ice-ares requested changes
Check the performance of those queries and optimise em

2023-04-22 11:29 UTC, ice-cronus commented on go.mod
> +	github.com/quic-go/quic-go => github.com/quic-go/quic-go v0.33.0
cuz newest quic-go breaked compatibility and imroc/req [does not work anymore](https://github.com/imroc/req/issues/232)

2023-04-22 11:38 UTC, ice-cronus commented on users/users_referrals.go
> +	elapsedDaysSinceLastRefCountsUpdate := int(nowMidnight.Sub(*res.Date.Time).Nanoseconds() / int64(hoursInOneDay*stdlibtime.Hour))
cuz we shift date only on referrals counts update (no worker which will do that for all users and updating counts for 25M of users makes no sense), so date in database can shows to date in the past. But as we know that referral counts was not changed since that time, we can use "TODAY" value in some amount of days (in range [lastRefUpdateDate, now])

2023-04-22 11:43 UTC, ice-cronus commented on users/users_get.go
> +			COALESCE(refs.t1_today, 0) 					  as t1_referral_count,
Yep, it seems I was wrong, that's not cummulative stats, so we also have to reset today to zero when date shifts, will redo that, and it seems we need new fields for total, yep.

2023-04-22 11:53 UTC, ice-cronus commented on users/users_referrals.go
> +			   COALESCE((SELECT t2_today from referral_acquisition_history where user_id = t2.id),0) AS t2,
to update it's T2 counts if I get a new referral. And we need a value to verify it on WHERE updating step to avoid race condition and verify if values were not changed

2023-04-22 12:21 UTC, ice-cronus commented on users/users_referrals.go
> +			   WHERE ((user_id = $2 AND date = $1) OR user_id = t2.id)
Nope, why? We're gonna update both users in one query, if possible

2023-04-22 12:54 UTC, ice-cronus commented on users/users_referrals.go
> +            UNION SELECT NULL as id) tmp LIMIT 1
In increment referrals query we need it to avoid double incrementing for the user, cuz when u setup a referral for 1st time, it points to the same user in database. And I used the same logic in all queries as well, but that case it seems to be unreachable in date shifting, cuz user cannot have referrals if he did not completed the sign in flow, I think we can remove it from here, I will do that.

2023-04-22 16:03 UTC, ice-ares commented on users/users_referrals.go
> +			   WHERE ((user_id = $2 AND date = $1) OR user_id = t2.id)
They're the same value

2023-04-22 16:05 UTC, ice-ares commented on users/users_referrals.go
> +            UNION SELECT NULL as id) tmp LIMIT 1
U already check to make sure usr.ReferredBy is properly checked, so u're not gonna have that sql running in that case

2023-04-22 16:08 UTC, ice-ares commented on users/users_referrals.go
> +			   COALESCE((SELECT t2_today from referral_acquisition_history where user_id = t2.id),0) AS t2,
Right. Make sure u dont double increase values in this new table. Cuz u can get the same message twice from the broker

2023-04-22 16:09 UTC, ice-ares commented on users/users_referrals.go
> +	elapsedDaysSinceLastRefCountsUpdate := int(nowMidnight.Sub(*res.Date.Time).Nanoseconds() / int64(hoursInOneDay*stdlibtime.Hour))
I see, ok

2023-04-25 09:43 UTC, ice-cronus commented on users/users_referrals.go
> +			   COALESCE((SELECT t2_today from referral_acquisition_history where user_id = t2.id),0) AS t2,
What's the best way to simulate duplicated message? Double call to rpk topic produce with an & or is there a better way?

2023-04-25 09:52 UTC, ice-ares commented on users/users_referrals.go
> +			   COALESCE((SELECT t2_today from referral_acquisition_history where user_id = t2.id),0) AS t2,
Yea, send the same message twice

2023-04-25 11:08 UTC, ice-cronus commented on users/users_referrals.go
> +			   WHERE ((user_id = $2 AND date = $1) OR user_id = t2.id)
But they are not the same. $2 is userSnapshot.referredBy (updated user is T1 of $2), t2.id is referredBy of  userSnapshot.referredBy (t minus 1?) (updated user is T2 of t2.id)

2023-04-27 11:57 UTC, ice-ares requested changes

2023-04-27 11:57 UTC, ice-ares commented on users/DDL.sql
> +CREATE INDEX IF NOT EXISTS users_referred_by_id_ix ON users (referred_by, id);
U already have one on referred by

2023-04-27 11:57 UTC, ice-ares commented on users/DDL.sql
> +CREATE INDEX IF NOT EXISTS referral_acquisition_history_user_id_t1_t2_date_ix ON referral_acquisition_history (date, user_id, t1_today, t2_today);
Why do u need this?

2023-04-27 11:57 UTC, ice-ares commented on users/DDL.sql
> +     LAST_PROCESSED_REFERRAL TEXT DEFAULT ''
Whats this for?

2023-04-27 11:57 UTC, ice-ares commented on users/users_referrals.go
> +		date,
Select * and make fields pointers to stuff to make sure the field order is matched. Do this for all other sqls. And also make sure u always select * in sqls and either make columns non null with a default or add pointers in structs.

Or do none of the above and add db tags, but select * everything

2023-04-27 11:57 UTC, ice-ares commented on users/users_referrals.go
> +	if lastProcessedReferralID == t1Referral {
Nope, dont do that cuz its error prone. If N referrals register at the same time u're gonna have alot of retries that throttle the consumer. Follow the same pattern for actions in husky/analytics.

And transform the insert and update ops into a single merge one. Check if u can use that for shifting as well

2023-04-27 12:27 UTC, ice-cronus commented on users/DDL.sql
> +CREATE INDEX IF NOT EXISTS users_referred_by_id_ix ON users (referred_by, id);
Yep, I have, but psql works much faster when the fields in comparsion are in the same index (and we have a lot of referred_by != id in this PR and in user search as well.

2023-04-27 12:30 UTC, ice-cronus commented on users/DDL.sql
> +CREATE INDEX IF NOT EXISTS referral_acquisition_history_user_id_t1_t2_date_ix ON referral_acquisition_history (date, user_id, t1_today, t2_today);
to filtering using the same index for race condition detection in case if value was incremented by another routine. But this one is speedup the queries less than that referred_by, id index, so this one is optional.

2023-04-27 14:28 UTC, ice-ares commented on users/DDL.sql
> +CREATE INDEX IF NOT EXISTS users_referred_by_id_ix ON users (referred_by, id);
Then keep only 1

2023-04-27 15:59 UTC, ice-cronus commented on users/users_referrals.go
> +	if lastProcessedReferralID == t1Referral {
I tried, but I need those with (...) t0 ... from t0 to get id of t0 user (otherwise I get sql error "missing FROM-clause entry for table "t0" , and insert does not support from clause. And it seems we cant apply subquery approach as well, cuz it still requires FROM, one way I see to combine them into one query is to use subqueries for each appearance of t0.id which is much worse

2023-04-27 16:03 UTC, ice-cronus commented on users/users_referrals.go
> +	if lastProcessedReferralID == t1Referral {
About husky / analytics, do u mean approach with msg.Timestamp? Is it unique enough?

2023-04-27 16:04 UTC, ice-ares commented on users/users_referrals.go
> +	if lastProcessedReferralID == t1Referral {
U can run 2 consecutive queries, no problem. Getting data is not an issue, changing is

2023-04-27 16:05 UTC, ice-ares commented on users/users_referrals.go
> +	if lastProcessedReferralID == t1Referral {
Also, insert works with select: insert into select, update works with from, and i think merge does as well

2023-04-27 16:07 UTC, ice-ares commented on users/users_referrals.go
> +	if lastProcessedReferralID == t1Referral {
> About husky / analytics, do u mean approach with msg.Timestamp? Is it unique enough?

The timestamp is a ttl actually. The uniqueness is custom, an user defined uuid in that case

2023-04-27 16:09 UTC, ice-ares commented on users/users_referrals.go
> +	if lastProcessedReferralID == t1Referral {
You insert into a table with a ttl, with information that makes each message unique ( in ur cass rhe referral id), if data ia already there insert will fail and u return without +1ing again.

then periodically, u remove entries older then that timestamp

2023-05-19 10:46 UTC, ice-ares commented on users/DDL.sql
> +                            processed_at            TIMESTAMP,
make this the first column

2023-05-19 14:10 UTC, merged