Get referral acquisition history
ice-blockchain/eskimo pull request #7
Opened 2022-05-16 14:22 UTC by kfedor

2022-05-17 19:40 UTC, kfedor commented on users/users_referrals.go
> +	return results[0].Count, nil
it was initial version

2022-05-17 22:46 UTC, azayats-leftclick commented on users/users_referrals.go
> +	today := time.Now().UTC().Unix() / 86400   //nolint:gomnd //This is number of seconds in day
candidate to const?

2022-05-18 06:25 UTC, kfedor commented on users/users_referrals.go
> +	today := time.Now().UTC().Unix() / 86400   //nolint:gomnd //This is number of seconds in day
function call is always not a const in go

2022-05-18 12:32 UTC, victor-oancea-leftclick-io requested changes

2022-05-18 12:32 UTC, victor-oancea-leftclick-io commented on users/users_referrals.go
> +	var results []referralAcquisition
array of pointers, always, performance is better for unmarshslling

2022-05-18 12:32 UTC, victor-oancea-leftclick-io commented on users/users_referrals.go
> +		"AND -1*(created_at/:nsec_to_days-:today) IN (%v) "+
created_at >= :pastNanos and created_at <= :nowNanos

the same for all sqls

2022-05-18 12:32 UTC, victor-oancea-leftclick-io commented on users/users_referrals.go
> +	sql := fmt.Sprintf("SELECT COUNT(*), created_at FROM users WHERE referred_by IN (%v) "+
the column you return is the same one you group by

2022-05-18 12:32 UTC, victor-oancea-leftclick-io commented on users/users_referrals.go
> +		"GROUP BY (created_at/:nsec_to_days-:today) ORDER BY created_at DESC", sql1, daysRange)
you could do (created_at - :pastNanos)/ 8.64E13, it would give you 1,2,3,4,5

2022-05-18 12:32 UTC, victor-oancea-leftclick-io commented on users/users_referrals.go
> +func (u *users) getT2Stats(id UserID, nSecToDays, today int64, daysRange string) ([]referralAcquisition, error) {
lets have 1 big sql for both, and try not to use union.

Also, pls lets stop breaking the sql into small pieces, lets have a single var big sql without any %v

2022-05-18 13:58 UTC, kfedor commented on users/users_referrals.go
> +		"AND -1*(created_at/:nsec_to_days-:today) IN (%v) "+
mb "between :pastnanos and :nownanos" ?
btw using such case I can't query several days in single query

2022-05-18 14:02 UTC, kfedor commented on users/users_referrals.go
> +func (u *users) getT2Stats(id UserID, nSecToDays, today int64, daysRange string) ([]referralAcquisition, error) {
ok i'll try
but why one SQL with two queries is better then two sqls ? db will execute two.
two sqls is easier to read and fix

2022-05-18 14:47 UTC, kfedor commented on users/users_referrals.go
> +	var results []referralAcquisition
done

2022-05-18 16:25 UTC, victor-oancea-leftclick-io commented on users/users_referrals.go
> +		"AND -1*(created_at/:nsec_to_days-:today) IN (%v) "+
You check timestamps in a range

2022-05-18 16:26 UTC, victor-oancea-leftclick-io commented on users/users_referrals.go
> +		"AND -1*(created_at/:nsec_to_days-:today) IN (%v) "+
[{days}*8,64E13, nowTS]

2022-05-18 16:26 UTC, victor-oancea-leftclick-io commented on users/users_referrals.go
> +	sql := fmt.Sprintf("SELECT COUNT(*), created_at FROM users WHERE referred_by IN (%v) "+
Its gonna be a different value

2022-05-18 16:27 UTC, victor-oancea-leftclick-io commented on users/users_referrals.go
> +func (u *users) getT2Stats(id UserID, nSecToDays, today int64, daysRange string) ([]referralAcquisition, error) {
Cuz of the RTT

2022-05-19 07:09 UTC, kfedor commented on users/users_referrals.go
> +	sql := fmt.Sprintf("SELECT COUNT(*), created_at FROM users WHERE referred_by IN (%v) "+
why? I group by days gone and output by days gone

2022-05-19 07:26 UTC, victor-oancea-leftclick-io commented on users/users_referrals.go
> +	sql := fmt.Sprintf("SELECT COUNT(*), created_at FROM users WHERE referred_by IN (%v) "+
You need to group by the date, and return the date . 2022-05-19

2022-05-19 07:45 UTC, kfedor commented on users/users_referrals.go
> +		"GROUP BY (created_at/:nsec_to_days-:today) ORDER BY created_at DESC", sql1, daysRange)
sql := fmt.Sprintf("SELECT COUNT(*), created_at FROM users WHERE referred_by IN "+
		"(SELECT id FROM USERS WHERE REFERRED_BY = :user_id AND -1*((created_at-:today)/:nsec_to_days) IN (%v)) "+
		"AND -1*((created_at-:today)/:nsec_to_days) IN (%v) "+
		"GROUP BY (created_at-:today)/:nsec_to_days ORDER BY created_at DESC", daysRange, daysRange)

where :today is time.Now().UTC().UnixNano()
nsec_to_days is 8.64E13
right?

2022-05-19 08:30 UTC, kfedor commented on users/users_referrals.go
> +func (u *users) getT2Stats(id UserID, nSecToDays, today int64, daysRange string) ([]referralAcquisition, error) {
how to do this?
SELECT ( SELECT COUNT(*) ), ( SELECT COUNT(*) ) FROM 
is working
but 
SELECT ( SELECT COUNT(*), created_at ), ( SELECT COUNT(*), created_at ) FROM 
fails
are there good SQL clients for tarantool ?

2022-05-19 09:39 UTC, victor-oancea-leftclick-io commented on users/users_referrals.go
> +		"GROUP BY (created_at/:nsec_to_days-:today) ORDER BY created_at DESC", sql1, daysRange)
Forget about it, ill do the sql, fix the other comments

2022-05-20 14:06 UTC, victor-oancea-leftclick-io requested changes

2022-05-20 14:06 UTC, victor-oancea-leftclick-io commented on users/users_referrals.go
> +		CAST(TOTAL(referrals.t1) AS INT),
put the aliases back

2022-05-20 19:42 UTC, kfedor commented on users/users_referrals.go
> +		CAST(TOTAL(referrals.t1) AS INT),
done, why do they matter?

2022-05-20 21:41 UTC, victor-oancea-leftclick-io commented on users/users_referrals.go
> +		CAST(TOTAL(referrals.t1) AS INT),
for the same reason naming funcs, methods, vars, args properly matters, so ppl would better understand whats going on

2022-05-23 08:06 UTC, nusanovkornilov-leftclick submitted a review, later dismissed

2022-05-23 08:50 UTC, nusanovkornilov-leftclick approved these changes

2022-05-23 08:51 UTC, merged